import type { Lesson } from './types'

export const ENGLISH_LESSONS: Lesson[] = [
  {
    id: 'en-to-be',
    language: 'en',
    level: 'A1',
    title: 'Глагол to be: am, is, are',
    summary: 'Как сказать «я студент», «она дома», «мы не устали».',
    theory: [
      {
        text: 'В английском предложении всегда есть глагол. Там, где по-русски его нет («Я студент», «Она дома»), ставится **to be** в нужной форме.',
        table: {
          head: ['Кто', 'Форма', 'Сокращение'],
          rows: [['I', 'am', "I'm"], ['he / she / it', 'is', "he's, she's, it's"], ['we / you / they', 'are', "we're, you're, they're"]],
        },
        examples: [
          { text: 'I **am** a student.', translation: 'Я студент.' },
          { text: 'She **is** at home.', translation: 'Она дома.' },
        ],
      },
      {
        heading: 'Отрицание и вопрос',
        text: 'В отрицании **not** ставится после глагола: is not = **isn’t**, are not = **aren’t**, а am not сокращается только как **I’m not**. В вопросе глагол переходит на место перед подлежащим.',
        examples: [
          { text: "She **isn't** at home.", translation: 'Её нет дома.' },
          { text: '**Are** you tired?', translation: 'Ты устал?' },
          { text: "I**'m not** a teacher.", translation: 'Я не учитель.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'My brother ___ a doctor.', options: ['am', 'is', 'are'], answer: 1, explain: 'My brother — это he, поэтому is.' },
      { kind: 'choice', prompt: 'We ___ from Kyiv.', options: ['is', 'am', 'are'], answer: 2, explain: 'С we всегда are.' },
      { kind: 'input', prompt: 'I ___ hungry.', hint: 'to be', answers: ['am', "'m"], explain: 'С I — только am: I am hungry (I’m hungry).' },
      { kind: 'input', prompt: '___ they at school?', hint: 'to be, вопрос', answers: ['are'], explain: 'В вопросе глагол стоит первым: Are they at school?' },
      { kind: 'choice', prompt: 'It ___ cold today.', options: ["isn't", "aren't", 'am not'], answer: 0, explain: 'It → is, в отрицании isn’t.' },
      { kind: 'input', prompt: 'You ___ late.', hint: 'to be + not', answers: ["aren't", 'are not'], explain: 'You → are, отрицание are not / aren’t.' },
      { kind: 'order', translation: 'Твоя сестра — студентка?', answer: 'Is your sister a student?', explain: 'Вопрос начинается с глагола: Is your sister…' },
      { kind: 'order', translation: 'Нас нет дома.', answer: 'We are not at home.' },
      { kind: 'choice', prompt: 'The children ___ in the garden.', options: ['is', 'are', 'am'], answer: 1, explain: 'The children — это they, поэтому are.' },
      { kind: 'input', prompt: 'This ___ my friend Anna.', hint: 'to be', answers: ['is', "'s"], explain: 'This → is.' },
      { kind: 'choice', prompt: '___ your parents at home?', options: ['Is', 'Are', 'Am'], answer: 1, explain: 'Your parents = they: Are your parents…?' },
      { kind: 'order', translation: 'Я не голоден, я устал.', answer: "I'm not hungry, I'm tired." },
    ],
  },
  {
    id: 'en-present-simple',
    language: 'en',
    level: 'A1',
    title: 'Present Simple: привычки и факты',
    summary: 'I work, she works: что происходит регулярно и что верно всегда.',
    theory: [
      {
        text: 'Present Simple описывает привычки, то, что происходит регулярно, и общие факты. Подсказки: **always, usually, often, sometimes, never, every day**.',
        examples: [
          { text: 'I **work** in a bank.', translation: 'Я работаю в банке.' },
          { text: 'Water **boils** at 100 °C.', translation: 'Вода кипит при 100 °C.' },
        ],
      },
      {
        heading: 'Окончание -s у he, she, it',
        text: 'С he, she, it к глаголу добавляется **-s**: works, plays. После -s, -sh, -ch, -x, -o пишется **-es**: watches, goes. Согласная + y меняется на **-ies**: study → studies. Have превращается в **has**.',
        examples: [
          { text: 'She **watches** the news every evening.', translation: 'Она каждый вечер смотрит новости.' },
          { text: 'He **has** two cats.', translation: 'У него две кошки.' },
        ],
      },
      {
        heading: 'Вопрос и отрицание',
        text: 'Нужен вспомогательный глагол **do**, а с he, she, it — **does**. После does глагол теряет -s.',
        examples: [
          { text: '**Do** you **speak** English?', translation: 'Ты говоришь по-английски?' },
          { text: "She **doesn't eat** meat.", translation: 'Она не ест мясо.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'She ___ coffee every morning.', options: ['drink', 'drinks', 'drinking'], answer: 1, explain: 'She + глагол с -s: drinks.' },
      { kind: 'input', prompt: 'He ___ TV in the evening.', hint: 'watch', answers: ['watches'], explain: 'После -ch добавляется -es: watches.' },
      { kind: 'input', prompt: 'My son ___ at university.', hint: 'study', answers: ['studies'], explain: 'Согласная + y → -ies: studies.' },
      { kind: 'choice', prompt: '___ you speak Spanish?', options: ['Do', 'Does', 'Are'], answer: 0, explain: 'С you вопрос строится с do.' },
      { kind: 'choice', prompt: "Tom doesn't ___ meat.", options: ['eats', 'eat', 'eating'], answer: 1, explain: 'После doesn’t глагол без -s.' },
      { kind: 'input', prompt: 'They ___ in London.', hint: 'not / live', answers: ["don't live", 'do not live'], explain: 'They → do not / don’t + live.' },
      { kind: 'choice', prompt: 'We ___ to the cinema on Fridays.', options: ['goes', 'go', 'going'], answer: 1, explain: 'С we глагол без окончания.' },
      { kind: 'order', translation: 'Твой брат играет в футбол?', answer: 'Does your brother play football?', explain: 'Does + подлежащее + глагол без -s.' },
      { kind: 'input', prompt: 'She ___ to work by bus.', hint: 'go', answers: ['goes'], explain: 'После -o добавляется -es: goes.' },
      { kind: 'choice', prompt: 'My parents ___ in a small town.', options: ['lives', 'live', 'living'], answer: 1, explain: 'My parents = they: live без -s.' },
      { kind: 'input', prompt: '___ your sister like cats?', hint: 'вспомогательный глагол', answers: ['does'], explain: 'Your sister = she: Does…?' },
      { kind: 'choice', prompt: 'He ___ never late.', options: ['is', 'does', 'do'], answer: 0, explain: 'Late — прилагательное, нужен to be: He is never late.' },
    ],
  },
  {
    id: 'en-there-is',
    language: 'en',
    level: 'A1',
    title: 'There is / there are: что где есть',
    summary: 'Как сказать «на столе кошка», «в городе два музея».',
    theory: [
      {
        text: 'Когда сообщают, что что-то **есть** или **находится** где-то, английское предложение начинается с **there is** (одна вещь) или **there are** (несколько). Место обычно стоит в конце, а перевод начинают с него.',
        examples: [
          { text: '**There is** a cat on the table.', translation: 'На столе (сидит) кошка.' },
          { text: '**There are** two museums in our town.', translation: 'В нашем городе два музея.' },
        ],
      },
      {
        heading: 'Отрицание и вопрос',
        text: 'В отрицании — **there isn’t / there aren’t**, часто с **any**: there aren’t any chairs. В вопросе is / are встаёт вперёд: **Is there…? Are there…?** Краткий ответ: Yes, there is. / No, there aren’t.',
        examples: [
          { text: "There **isn't** any milk.", translation: 'Молока нет.' },
          { text: '**Are there** any shops near here?', translation: 'Здесь рядом есть магазины?' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'There ___ a park near my house.', options: ['is', 'are', 'am'], answer: 0, explain: 'Один парк — there is.' },
      { kind: 'choice', prompt: 'There ___ three bedrooms in the flat.', options: ['is', 'are', 'be'], answer: 1, explain: 'Три спальни — множественное число, there are.' },
      { kind: 'input', prompt: '___ there a bank in this street?', hint: 'to be, вопрос', answers: ['is'], explain: 'Один банк, вопрос: Is there…?' },
      { kind: 'input', prompt: "There ___ any eggs in the fridge.", hint: 'to be + not', answers: ["aren't", 'are not'], explain: 'Eggs — множественное число: there aren’t any eggs.' },
      { kind: 'choice', prompt: 'Are there any students in the room? — Yes, there ___.', options: ['is', 'are', "aren't"], answer: 1, explain: 'Краткий ответ повторяет are: Yes, there are.' },
      { kind: 'choice', prompt: 'There is ___ apple on the plate.', options: ['a', 'an', 'some'], answer: 1, explain: 'Одно яблоко, гласный звук — an apple.' },
      { kind: 'choice', prompt: "There isn't ___ water in the bottle.", options: ['some', 'any', 'a'], answer: 1, explain: 'В отрицании — any.' },
      { kind: 'order', translation: 'В комнате много книг.', answer: 'There are a lot of books in the room.' },
      { kind: 'choice', prompt: 'There ___ some milk in the fridge.', options: ['is', 'are'], answer: 0, explain: 'Milk — неисчисляемое, there is.' },
      { kind: 'input', prompt: '___ there any good restaurants here?', hint: 'to be', answers: ['are'], explain: 'Restaurants — множественное: Are there…?' },
      { kind: 'choice', prompt: 'How many people ___ there in your family?', options: ['is', 'are', 'be'], answer: 1, explain: 'People — множественное: are there.' },
      { kind: 'order', translation: 'Рядом с моим домом нет парка.', answer: "There isn't a park near my house." },
    ],
  },
  {
    id: 'en-present-continuous',
    language: 'en',
    level: 'A2',
    title: 'Present Continuous: что происходит сейчас',
    summary: 'I am reading — действие в процессе, прямо сейчас или в эти дни.',
    theory: [
      {
        text: 'Present Continuous = **am / is / are + глагол с -ing**. Так говорят о том, что происходит прямо сейчас или в этот период. Подсказки: **now, at the moment, today, this week, Look!**',
        examples: [
          { text: "I**'m reading** a great book this month.", translation: 'В этом месяце я читаю отличную книгу.' },
          { text: 'Look! It **is raining**.', translation: 'Смотри! Идёт дождь.' },
        ],
      },
      {
        heading: 'Как пишется -ing',
        text: 'Немая e выпадает: make → **making**. Короткий глагол с одной гласной перед согласной удваивает её: run → **running**, sit → **sitting**. ie меняется на y: lie → **lying**.',
      },
      {
        heading: 'Simple или Continuous?',
        text: 'Present Simple — регулярно и всегда, Present Continuous — сейчас. Глаголы состояния (**know, like, want, understand, believe**) обычно не ставятся в Continuous.',
        examples: [
          { text: 'He usually **walks** to work, but today he **is taking** a taxi.', translation: 'Обычно он ходит на работу пешком, но сегодня едет на такси.' },
          { text: 'I **know** the answer.', translation: 'Я знаю ответ. (не I’m knowing)' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Look! It ___.', options: ['rains', 'is raining', 'rain'], answer: 1, explain: 'Look! — действие прямо сейчас: is raining.' },
      { kind: 'input', prompt: 'She ___ an email right now.', hint: 'write', answers: ['is writing', "'s writing"], explain: 'is + writing: немая e выпадает.' },
      { kind: 'input', prompt: 'We ___ in the garden at the moment.', hint: 'sit', answers: ['are sitting', "'re sitting"], explain: 'are + sitting: t удваивается.' },
      { kind: 'choice', prompt: 'I ___ what you mean.', options: ['understand', 'am understanding', 'understanding'], answer: 0, explain: 'Understand — глагол состояния, остаётся в Present Simple.' },
      { kind: 'choice', prompt: 'He usually ___ to work by bus.', options: ['goes', 'is going', 'go'], answer: 0, explain: 'Usually — привычка, значит Present Simple.' },
      { kind: 'choice', prompt: '___ you listening to me?', options: ['Do', 'Are', 'Is'], answer: 1, explain: 'Вопрос в Continuous начинается с am / is / are: Are you listening?' },
      { kind: 'input', prompt: 'They ___ TV now.', hint: 'not / watch', answers: ["aren't watching", 'are not watching'], explain: 'They are not / aren’t + watching.' },
      { kind: 'order', translation: 'Что ты сейчас делаешь?', answer: 'What are you doing now?' },
      { kind: 'input', prompt: 'Be quiet! The baby ___.', hint: 'sleep', answers: ['is sleeping', "'s sleeping"], explain: 'Прямо сейчас: is sleeping.' },
      { kind: 'choice', prompt: 'I ___ the answer to this question.', options: ['know', 'am knowing', 'knowing'], answer: 0, explain: 'Know — глагол состояния, Present Simple.' },
      { kind: 'input', prompt: 'He ___ in a hotel this week.', hint: 'stay', answers: ['is staying', "'s staying"], explain: 'Временная ситуация «на этой неделе»: is staying.' },
      { kind: 'choice', prompt: 'Where ___ you going?', options: ['do', 'are', 'is'], answer: 1, explain: 'Continuous: Where are you going?' },
    ],
  },
  {
    id: 'en-past-simple',
    language: 'en',
    level: 'A2',
    title: 'Past Simple: что было в прошлом',
    summary: 'Worked, went, saw: законченные действия в прошлом.',
    theory: [
      {
        text: 'Past Simple — для законченных действий в прошлом. Подсказки: **yesterday, last week, two years ago, in 2010**. Правильные глаголы получают **-ed**: work → worked, live → lived, stop → **stopped**, study → **studied**.',
        examples: [
          { text: 'We **visited** Paris last summer.', translation: 'Прошлым летом мы были в Париже.' },
        ],
      },
      {
        heading: 'Неправильные глаголы',
        text: 'Часть глаголов меняется целиком — их нужно запомнить.',
        table: {
          head: ['Глагол', 'Past Simple', 'Перевод'],
          rows: [['go', 'went', 'идти, ехать'], ['see', 'saw', 'видеть'], ['have', 'had', 'иметь'], ['make', 'made', 'делать'], ['take', 'took', 'брать'], ['buy', 'bought', 'покупать']],
        },
      },
      {
        heading: 'Вопрос и отрицание',
        text: 'Нужен **did**, а глагол возвращается в начальную форму — и для правильных, и для неправильных.',
        examples: [
          { text: '**Did** you **see** the film?', translation: 'Ты посмотрел фильм?' },
          { text: "I **didn't go** to work yesterday.", translation: 'Вчера я не ходил на работу.' },
        ],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'We ___ our grandparents last weekend.', hint: 'visit', answers: ['visited'], explain: 'Правильный глагол: visit + -ed.' },
      { kind: 'input', prompt: 'She ___ to Spain two years ago.', hint: 'go', answers: ['went'], explain: 'Go — неправильный глагол: went.' },
      { kind: 'choice', prompt: 'I ___ him yesterday.', options: ['see', 'saw', 'seen'], answer: 1, explain: 'Yesterday → Past Simple: saw.' },
      { kind: 'choice', prompt: 'Did you ___ the tickets?', options: ['buy', 'bought', 'buys'], answer: 0, explain: 'После did — начальная форма: buy.' },
      { kind: 'input', prompt: 'He ___ the car at the corner.', hint: 'stop', answers: ['stopped'], explain: 'Короткий глагол: согласная удваивается — stopped.' },
      { kind: 'input', prompt: 'They ___ time for breakfast.', hint: 'not / have', answers: ["didn't have", 'did not have'], explain: 'did not / didn’t + have.' },
      { kind: 'choice', prompt: 'When ___ the film start yesterday?', options: ['did', 'does', 'do'], answer: 0, explain: 'Yesterday → вопрос с did.' },
      { kind: 'order', translation: 'Я не понял вопрос.', answer: "I didn't understand the question." },
      { kind: 'input', prompt: 'I ___ a great book last month.', hint: 'read', answers: ['read'], explain: 'Read — неправильный глагол: пишется так же, читается [red].' },
      { kind: 'choice', prompt: 'Where ___ you go on holiday?', options: ['did', 'were', 'do'], answer: 0, explain: 'Вопрос в прошлом с обычным глаголом — did.' },
      { kind: 'input', prompt: 'We ___ at home last night.', hint: 'be', answers: ['were'], explain: 'To be в прошедшем: was / were. We → were.' },
      { kind: 'input', prompt: 'She ___ me a present for my birthday.', hint: 'buy', answers: ['bought'], explain: 'buy → bought.' },
    ],
  },
  {
    id: 'en-articles',
    language: 'en',
    level: 'A2',
    title: 'Артикли a, an, the',
    summary: 'Когда «какой-то», когда «тот самый», а когда артикль не нужен.',
    theory: [
      {
        text: '**A / an** — один из многих, о котором говорят впервые. **An** ставится перед гласным звуком: an apple, an hour (h не читается). Но **a university** — слово начинается со звука [ju].',
        examples: [{ text: 'I saw **a** dog in the park.', translation: 'Я видел в парке собаку.' }],
      },
      {
        text: '**The** — конкретный, уже знакомый или единственный в своём роде предмет.',
        examples: [
          { text: '**The** dog was very big.', translation: 'Та собака была очень большой.' },
          { text: '**The** sun is shining.', translation: 'Светит солнце.' },
        ],
      },
      {
        heading: 'Без артикля',
        text: 'Множественное число и неисчисляемое в общем смысле, имена и большинство стран. Исключения со словами states, kingdom, republic: **the USA, the UK**.',
        examples: [
          { text: 'I like cats.', translation: 'Я люблю кошек.' },
          { text: 'Anna lives in France.', translation: 'Анна живёт во Франции.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'I have ___ idea!', options: ['a', 'an', 'the'], answer: 1, explain: 'Idea начинается с гласного звука: an idea.' },
      { kind: 'choice', prompt: 'She is ___ university student.', options: ['a', 'an', '—'], answer: 0, explain: 'University звучит [ju:] — это согласный звук, поэтому a.' },
      { kind: 'choice', prompt: '___ sun is very bright today.', options: ['A', 'The', '—'], answer: 1, explain: 'Солнце одно — the sun.' },
      { kind: 'choice', prompt: 'I bought a book and a pen. ___ book is very interesting.', options: ['A', 'The', '—'], answer: 1, explain: 'Книгу уже упомянули — теперь the book.' },
      { kind: 'choice', prompt: '___ dogs are friendly animals.', options: ['The', 'A', '—'], answer: 2, explain: 'Собаки вообще, в общем смысле — без артикля.' },
      { kind: 'choice', prompt: 'We waited for ___ hour.', options: ['a', 'an', 'the'], answer: 1, explain: 'В hour h не читается: an hour.' },
      { kind: 'choice', prompt: 'He lives in ___ USA.', options: ['—', 'the', 'a'], answer: 1, explain: 'the USA — the United States.' },
      { kind: 'order', translation: 'На крыше кошка.', answer: 'There is a cat on the roof.' },
      { kind: 'choice', prompt: 'My sister is ___ engineer.', options: ['a', 'an', 'the'], answer: 1, explain: 'Профессия — a / an; engineer начинается с гласного звука.' },
      { kind: 'choice', prompt: 'Can you close ___ door, please?', options: ['a', 'the', '—'], answer: 1, explain: 'Понятно, какая дверь, — the.' },
      { kind: 'choice', prompt: 'I usually have ___ breakfast at eight.', options: ['a', 'the', '—'], answer: 2, explain: 'Приёмы пищи в общем смысле — без артикля.' },
      { kind: 'choice', prompt: 'She plays ___ piano very well.', options: ['a', 'the', '—'], answer: 1, explain: 'С музыкальными инструментами — the.' },
    ],
  },
  {
    id: 'en-future',
    language: 'en',
    level: 'A2',
    title: 'Будущее: will и going to',
    summary: 'Решение на ходу, обещание или уже готовый план.',
    theory: [
      {
        heading: 'Will',
        text: '**Will + глагол** — для решений, принятых в момент речи, обещаний, предложений помощи и предсказаний «я думаю, что…». Сокращается до **’ll**, отрицание — **won’t**.',
        examples: [
          { text: "It's cold. I**'ll close** the window.", translation: 'Холодно. Я закрою окно. (решил сейчас)' },
          { text: 'I think it **will rain** tomorrow.', translation: 'Думаю, завтра будет дождь.' },
          { text: "I **won't tell** anyone.", translation: 'Я никому не скажу.' },
        ],
      },
      {
        heading: 'Going to',
        text: '**am / is / are going to + глагол** — для планов и намерений, о которых думали заранее, и для предсказаний по тому, что видно сейчас.',
        examples: [
          { text: "We**'re going to buy** a car next year.", translation: 'В следующем году мы собираемся купить машину.' },
          { text: "Look at those clouds! It**'s going to rain**.", translation: 'Посмотри на тучи! Сейчас пойдёт дождь.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: "The phone is ringing. — I ___ answer it!", options: ["'ll", "'m going to", 'am'], answer: 0, explain: 'Решение принято прямо сейчас — will.' },
      { kind: 'choice', prompt: "We ___ visit Rome in May — we've already booked the hotel.", options: ['will', 'are going to', 'go to'], answer: 1, explain: 'Заранее продуманный план — going to.' },
      { kind: 'choice', prompt: "Be careful! You ___ fall!", options: ["'ll", "'re going to", 'are'], answer: 1, explain: 'Предсказание по тому, что видно сейчас, — going to.' },
      { kind: 'input', prompt: "Don't worry, I ___ tell your mum.", hint: 'will + not', answers: ["won't", 'will not'], explain: 'Обещание в отрицании: won’t.' },
      { kind: 'input', prompt: 'She ___ study medicine after school.', hint: 'going to', answers: ['is going to', "'s going to"], explain: 'Намерение: she is going to study.' },
      { kind: 'choice', prompt: 'I think Spain ___ win the match.', options: ['will', 'is going', 'wins'], answer: 0, explain: '«Я думаю, что…» — мнение о будущем, will.' },
      { kind: 'choice', prompt: 'These bags look heavy. I ___ help you.', options: ['am going', "'ll", 'help'], answer: 1, explain: 'Предложение помощи — will.' },
      { kind: 'order', translation: 'Что ты собираешься делать в выходные?', answer: 'What are you going to do at the weekend?' },
      { kind: 'choice', prompt: 'Look at the time! We ___ be late.', options: ["'re going to", 'will to', 'are'], answer: 0, explain: 'Вывод из того, что видно сейчас, — going to.' },
      { kind: 'input', prompt: 'I promise I ___ you tomorrow.', hint: 'will + call', answers: ['will call', "'ll call"], explain: 'Обещание: will call.' },
      { kind: 'choice', prompt: 'What ___ you going to cook tonight?', options: ['are', 'will', 'do'], answer: 0, explain: 'Going to строится с am / is / are.' },
      { kind: 'order', translation: 'Я думаю, ей понравится этот подарок.', answer: 'I think she will like this present.' },
    ],
  },
  {
    id: 'en-present-perfect',
    language: 'en',
    level: 'B1',
    title: 'Present Perfect: результат к настоящему',
    summary: 'I have done: прошлое, которое важно сейчас, и опыт «когда-либо».',
    theory: [
      {
        text: 'Present Perfect = **have / has + третья форма глагола** (worked, seen, done). Время действия не названо — важен результат сейчас или сам опыт.',
        examples: [
          { text: "I**'ve lost** my keys.", translation: 'Я потерял ключи. (и сейчас их нет)' },
          { text: '**Have** you ever **been** to Japan?', translation: 'Ты когда-нибудь был в Японии?' },
        ],
      },
      {
        heading: 'Подсказки',
        text: '**ever, never, already, yet, just** и период, который ещё не закончился: today, this week. С **for** (в течение) и **since** (с какого момента) — то, что началось в прошлом и продолжается: I’ve lived here **for** ten years / **since** 2015.',
        examples: [
          { text: "She **has just left**.", translation: 'Она только что ушла.' },
          { text: "We **haven't finished yet**.", translation: 'Мы ещё не закончили.' },
        ],
      },
      {
        heading: 'Perfect или Past Simple?',
        text: 'Если названо **когда** (yesterday, in 2019, last week, ago) — только Past Simple. Present Perfect не сочетается с законченным временем.',
        examples: [{ text: "I **saw** him yesterday. — I**'ve seen** him today.", translation: 'Я видел его вчера. — Я видел его сегодня.' }],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'I ___ this film three times.', hint: 'see', answers: ['have seen', "'ve seen"], explain: 'Опыт без указания времени: have seen.' },
      { kind: 'choice', prompt: 'She ___ to Paris in 2019.', options: ['has gone', 'went', 'has been'], answer: 1, explain: 'In 2019 — законченное время, Past Simple.' },
      { kind: 'choice', prompt: 'Have you finished your homework ___?', options: ['already', 'yet', 'just'], answer: 1, explain: 'В вопросах и отрицаниях в конце — yet.' },
      { kind: 'choice', prompt: "We've lived here ___ 2015.", options: ['for', 'since', 'ago'], answer: 1, explain: 'С точки во времени — since.' },
      { kind: 'choice', prompt: "They've known each other ___ ten years.", options: ['for', 'since', 'during'], answer: 0, explain: 'Длительность — for.' },
      { kind: 'input', prompt: 'He ___ his phone. He can’t call you.', hint: 'lose', answers: ['has lost', "'s lost"], explain: 'Результат важен сейчас: has lost.' },
      { kind: 'input', prompt: '___ you ever eaten sushi?', hint: 'have', answers: ['have'], explain: 'Вопрос об опыте: Have you ever…?' },
      { kind: 'order', translation: 'Я никогда не был в Лондоне.', answer: "I've never been to London." },
      { kind: 'choice', prompt: "I've ___ finished my essay — here it is.", options: ['yet', 'already', 'ever'], answer: 1, explain: 'Уже — already, в середине утверждения.' },
      { kind: 'input', prompt: 'They ___ married for five years.', hint: 'be', answers: ['have been', "'ve been"], explain: 'For five years до сих пор: have been.' },
      { kind: 'choice', prompt: 'When ___ you start learning English?', options: ['have', 'did', 'has'], answer: 1, explain: 'Вопрос When — о моменте в прошлом, Past Simple.' },
      { kind: 'choice', prompt: "She has ___ to the shop. She'll be back soon.", options: ['been', 'gone'], answer: 1, explain: 'Gone — ушла и ещё не вернулась; been — побывала и вернулась.' },
    ],
  },
  {
    id: 'en-conditionals',
    language: 'en',
    level: 'B1',
    title: 'Условные предложения: first и second',
    summary: 'If it rains, we’ll stay. If I were rich, I’d travel.',
    theory: [
      {
        heading: 'First conditional — реальное будущее',
        text: '**If + Present Simple, will + глагол.** Условие вполне возможно. После if будущее время не ставится!',
        examples: [
          { text: "If it **rains**, we**'ll stay** at home.", translation: 'Если пойдёт дождь, мы останемся дома.' },
          { text: "If you **don't hurry**, you**'ll miss** the bus.", translation: 'Если не поторопишься, опоздаешь на автобус.' },
        ],
      },
      {
        heading: 'Second conditional — воображаемое',
        text: '**If + Past Simple, would + глагол.** Ситуация маловероятна или нереальна сейчас. С to be часто говорят **were** для всех лиц: If I were you…',
        examples: [
          { text: "If I **had** more time, I**'d learn** Chinese.", translation: 'Если бы у меня было больше времени, я бы выучил китайский.' },
          { text: "If I **were** you, I **wouldn't do** that.", translation: 'На твоём месте я бы этого не делал.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: "If it ___ tomorrow, we'll go to the beach.", options: ['will be sunny', 'is sunny', 'was sunny'], answer: 1, explain: 'После if в first conditional — Present Simple.' },
      { kind: 'input', prompt: 'If you heat ice, it ___.', hint: 'melt, will', answers: ["will melt", "'ll melt", 'melts'], explain: 'Реальное следствие: will melt (для общих фактов можно и melts).' },
      { kind: 'choice', prompt: "If I ___ a million dollars, I'd buy an island.", options: ['have', 'had', 'would have'], answer: 1, explain: 'Воображаемое — second conditional: if + Past Simple.' },
      { kind: 'choice', prompt: 'If I were you, I ___ that job.', options: ['will take', 'would take', 'took'], answer: 1, explain: 'Совет «на твоём месте» — would.' },
      { kind: 'input', prompt: "If she ___ harder, she would pass.", hint: 'study', answers: ['studied'], explain: 'Second conditional: if + Past Simple — studied.' },
      { kind: 'choice', prompt: "We'll miss the train if we ___ now.", options: ["don't leave", "won't leave", "didn't leave"], answer: 0, explain: 'Часть с if может стоять второй, но время то же: Present Simple.' },
      { kind: 'choice', prompt: 'What would you do if you ___ the president?', options: ['are', 'were', 'will be'], answer: 1, explain: 'Нереальная ситуация: if you were.' },
      { kind: 'order', translation: 'Если я его увижу, я ему скажу.', answer: "If I see him, I'll tell him." },
      { kind: 'choice', prompt: 'If I ___ you, I would apologise.', options: ['am', 'were', 'will be'], answer: 1, explain: 'If I were you — совет «на твоём месте».' },
      { kind: 'input', prompt: 'If it ___ tomorrow, we’ll cancel the picnic.', hint: 'rain', answers: ['rains'], explain: 'После if — Present Simple: rains.' },
      { kind: 'choice', prompt: 'Unless you hurry, you ___ the train.', options: ['will miss', 'miss', 'would miss'], answer: 0, explain: 'Unless = if not; реальное будущее — will.' },
      { kind: 'order', translation: 'Что бы ты сделал, если бы выиграл в лотерею?', answer: 'What would you do if you won the lottery?' },
    ],
  },
  {
    id: 'en-passive',
    language: 'en',
    level: 'B1',
    title: 'Пассивный залог',
    summary: 'The letter was written: когда важно действие, а не кто его сделал.',
    theory: [
      {
        text: 'Passive = **to be в нужном времени + третья форма глагола**. Объект действия становится подлежащим. Кто сделал — добавляется через **by**, если это важно.',
        table: {
          head: ['Время', 'Актив', 'Пассив'],
          rows: [['Present Simple', 'They make cars here.', 'Cars are made here.'], ['Past Simple', 'Tom wrote the letter.', 'The letter was written by Tom.'], ['Present Perfect', 'Someone has stolen my bike.', 'My bike has been stolen.'], ['will', 'They will open a shop.', 'A shop will be opened.']],
        },
      },
      {
        heading: 'Когда нужен пассив',
        text: 'Когда исполнитель неизвестен, очевиден или не важен, а также в новостях, инструкциях, научных текстах.',
        examples: [
          { text: 'English **is spoken** all over the world.', translation: 'На английском говорят по всему миру.' },
          { text: 'The museum **was built** in 1890.', translation: 'Музей построили в 1890 году.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'This bridge ___ in 1932.', options: ['built', 'was built', 'is building'], answer: 1, explain: 'Мост построили (кто — не важно): was built.' },
      { kind: 'input', prompt: 'Coffee ___ in Brazil.', hint: 'grow, пассив', answers: ['is grown'], explain: 'Общий факт, Present Simple: is grown.' },
      { kind: 'input', prompt: 'My bike ___!', hint: 'steal, Present Perfect пассив', answers: ['has been stolen'], explain: 'has been + stolen.' },
      { kind: 'choice', prompt: 'The results ___ tomorrow.', options: ['will announce', 'will be announced', 'are announcing'], answer: 1, explain: 'Пассив в будущем: will be + V3.' },
      { kind: 'choice', prompt: '"Hamlet" was written ___ Shakespeare.', options: ['from', 'by', 'with'], answer: 1, explain: 'Исполнитель — через by.' },
      { kind: 'input', prompt: 'These photos ___ by my grandfather.', hint: 'take, Past Simple пассив', answers: ['were taken'], explain: 'Photos — множественное: were taken.' },
      { kind: 'choice', prompt: 'Smoking ___ in this building.', options: ["isn't allowed", "doesn't allow", "isn't allowing"], answer: 0, explain: 'Правило без исполнителя: isn’t allowed.' },
      { kind: 'order', translation: 'Окно разбили вчера.', answer: 'The window was broken yesterday.' },
      { kind: 'input', prompt: 'The windows ___ every week.', hint: 'clean, пассив', answers: ['are cleaned'], explain: 'Регулярно, Present Simple: are cleaned.' },
      { kind: 'choice', prompt: 'The new hospital ___ next year.', options: ['will be opened', 'will open', 'is opened'], answer: 0, explain: 'Больницу откроют — пассив в будущем.' },
      { kind: 'choice', prompt: 'My car ___ yet.', options: ["hasn't been repaired", "hasn't repaired", "wasn't repaired"], answer: 0, explain: 'Yet → Present Perfect пассив: hasn’t been repaired.' },
      { kind: 'order', translation: 'Этот роман был написан в 1960 году.', answer: 'This novel was written in 1960.' },
    ],
  },
  {
    id: 'en-past-perfect',
    language: 'en',
    level: 'B2',
    title: 'Past Perfect и рассказ о прошлом',
    summary: 'Had done: что случилось раньше другого события в прошлом.',
    theory: [
      {
        text: 'Past Perfect = **had + третья форма**. Он показывает, что одно прошлое действие произошло **раньше** другого. Без него порядок событий бывает непонятен.',
        examples: [
          { text: 'When we arrived, the train **had left**.', translation: 'Когда мы приехали, поезд уже ушёл.' },
          { text: 'When we arrived, the train **left**.', translation: 'Когда мы приехали, поезд ушёл (в этот момент).' },
        ],
      },
      {
        heading: 'Три времени в рассказе',
        text: 'Past Simple — основная цепочка событий, Past Continuous — фон (что происходило), Past Perfect — то, что случилось ещё раньше. Часто с **already, just, before, after, by the time**.',
        examples: [
          { text: 'It **was raining**. I **got** home and **realised** I **had lost** my keys.', translation: 'Шёл дождь. Я пришёл домой и понял, что потерял ключи.' },
          { text: 'By the time she called, I **had** already **gone** to bed.', translation: 'К тому времени, как она позвонила, я уже лёг спать.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'When I got to the cinema, the film ___.', options: ['already started', 'had already started', 'has already started'], answer: 1, explain: 'Фильм начался раньше, чем я пришёл: had started.' },
      { kind: 'input', prompt: 'She was nervous because she ___ before.', hint: 'not / fly', answers: ["hadn't flown", 'had not flown'], explain: 'Опыт до момента в прошлом: hadn’t flown.' },
      { kind: 'input', prompt: 'After they ___ dinner, they went for a walk.', hint: 'have', answers: ['had had', "'d had"], explain: 'Сначала ужин: had had (had + had).' },
      { kind: 'choice', prompt: 'I ___ a shower when the phone rang.', options: ['had', 'was having', 'had had'], answer: 1, explain: 'Фон, процесс в момент звонка — Past Continuous.' },
      { kind: 'choice', prompt: 'By the time we arrived, everyone ___.', options: ['left', 'had left', 'was leaving'], answer: 1, explain: 'By the time — сигнал Past Perfect.' },
      { kind: 'input', prompt: 'I recognised him because I ___ him before.', hint: 'meet', answers: ['had met', "'d met"], explain: 'Встреча была раньше: had met.' },
      { kind: 'choice', prompt: 'He ___ the door, turned off the light and left.', options: ['locked', 'had locked', 'was locking'], answer: 0, explain: 'Цепочка действий по порядку — Past Simple.' },
      { kind: 'order', translation: 'Когда я проснулся, дождь уже закончился.', answer: 'When I woke up, the rain had already stopped.' },
      { kind: 'input', prompt: 'I didn’t want to see the film because I ___ it.', hint: 'already / see', answers: ['had already seen', "'d already seen"], explain: 'Видел раньше: had already seen.' },
      { kind: 'choice', prompt: 'She ___ never been abroad before 2010.', options: ['has', 'had', 'was'], answer: 1, explain: 'Опыт до момента в прошлом: had been.' },
      { kind: 'choice', prompt: 'When I arrived, Tom ___ dinner, so we sat down to eat.', options: ['cooked', 'was cooking', 'had cooked'], answer: 2, explain: 'Ужин уже был готов к моему приходу: had cooked.' },
      { kind: 'order', translation: 'Он понял, что забыл паспорт.', answer: 'He realised he had forgotten his passport.' },
    ],
  },
  {
    id: 'en-reported-speech',
    language: 'en',
    level: 'B2',
    title: 'Косвенная речь',
    summary: 'She said she was tired: как пересказать чужие слова.',
    theory: [
      {
        text: 'Когда пересказывают слова после **said** или **told**, время обычно сдвигается на шаг в прошлое, а местоимения и слова времени меняются по смыслу.',
        table: {
          head: ['Прямая речь', 'Косвенная речь'],
          rows: [['"I am tired."', 'She said (that) she was tired.'], ['"I’m working."', 'He said he was working.'], ['"I saw it."', 'She said she had seen it.'], ['"I will call."', 'He said he would call.'], ['"I can swim."', 'She said she could swim.']],
        },
      },
      {
        heading: 'Вопросы и просьбы',
        text: 'В пересказе вопроса порядок слов прямой, без do / did. Вопрос «да / нет» вводится **if / whether**. Просьбы и приказы — **told / asked + to + глагол**.',
        examples: [
          { text: 'She asked where **I lived**.', translation: '"Where do you live?" → Она спросила, где я живу.' },
          { text: 'He asked **if** I was hungry.', translation: '"Are you hungry?" → Он спросил, голоден ли я.' },
          { text: 'The teacher told us **to be** quiet.', translation: 'Учитель велел нам вести себя тихо.' },
        ],
      },
      {
        heading: 'Слова времени и места',
        text: 'now → **then**, today → **that day**, tomorrow → **the next day**, yesterday → **the day before**, here → **there**. После **say** не ставится лицо, после **tell** — обязательно: said that…, told me that…',
      },
    ],
    exercises: [
      { kind: 'input', prompt: '"I am busy." → She said she ___ busy.', answers: ['was'], explain: 'am → was.' },
      { kind: 'input', prompt: '"I will help you." → He said he ___ help me.', answers: ['would'], explain: 'will → would.' },
      { kind: 'choice', prompt: '"I lost my wallet." → He said he ___ his wallet.', options: ['lost', 'had lost', 'has lost'], answer: 1, explain: 'Past Simple → Past Perfect.' },
      { kind: 'choice', prompt: '"Where do you work?" → She asked me where ___.', options: ['do I work', 'I worked', 'did I work'], answer: 1, explain: 'Прямой порядок слов и сдвиг времени: where I worked.' },
      { kind: 'choice', prompt: '"Are you coming?" → He asked ___ I was coming.', options: ['that', 'if', 'what'], answer: 1, explain: 'Вопрос «да / нет» — if / whether.' },
      { kind: 'choice', prompt: 'She ___ me that she was leaving.', options: ['said', 'told', 'asked'], answer: 1, explain: 'С лицом (me) — told.' },
      { kind: 'input', prompt: '"Close the door!" → He told me ___ the door.', answers: ['to close'], explain: 'Приказ: told + to + глагол.' },
      { kind: 'order', translation: 'Она сказала, что позвонит на следующий день.', answer: 'She said she would call the next day.' },
      { kind: 'input', prompt: '"I can drive." → She said she ___ drive.', answers: ['could'], explain: 'can → could.' },
      { kind: 'choice', prompt: '"I’m leaving tomorrow." → He said he was leaving ___.', options: ['tomorrow', 'the next day', 'yesterday'], answer: 1, explain: 'tomorrow → the next day.' },
      { kind: 'choice', prompt: '"Don’t touch it!" → She told me ___ it.', options: ['not to touch', "don't touch", 'to not touching'], answer: 0, explain: 'Запрет: told + not to + глагол.' },
      { kind: 'input', prompt: '"Do you like jazz?" → He asked me ___ I liked jazz.', answers: ['if', 'whether'], explain: 'Вопрос «да / нет» — if / whether.' },
    ],
  },
  {
    id: 'en-third-conditional',
    language: 'en',
    level: 'B2',
    title: 'Third conditional и wish',
    summary: 'If I had known… — сожаления о прошлом, которое уже не изменить.',
    theory: [
      {
        heading: 'Third conditional',
        text: '**If + Past Perfect, would have + третья форма.** Речь о прошлом, которое пошло по-другому: условие не выполнилось.',
        examples: [
          { text: 'If I **had known**, I **would have helped** you.', translation: 'Если бы я знал, я бы тебе помог.' },
          { text: "If we **hadn't missed** the bus, we **wouldn't have been** late.", translation: 'Если бы мы не пропустили автобус, мы бы не опоздали.' },
        ],
      },
      {
        heading: 'Смешанные условия',
        text: 'Прошлое условие с последствием сейчас: **If + Past Perfect, would + глагол.**',
        examples: [{ text: "If I **had studied** medicine, I **would be** a doctor now.", translation: 'Если бы я учился на медика, я бы сейчас был врачом.' }],
      },
      {
        heading: 'I wish / if only',
        text: 'Сожаление о настоящем — **wish + Past Simple**; о прошлом — **wish + Past Perfect**; раздражение чужим поведением — **wish + would**.',
        examples: [
          { text: 'I wish I **lived** by the sea.', translation: 'Жаль, что я не живу у моря.' },
          { text: "I wish I **hadn't said** that.", translation: 'Жаль, что я это сказал.' },
          { text: 'I wish you **would stop** talking.', translation: 'Хоть бы ты перестал болтать.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'If you had told me, I ___ you.', options: ['would help', 'would have helped', 'had helped'], answer: 1, explain: 'Третий тип: would have + V3.' },
      { kind: 'input', prompt: 'If she ___ earlier, she would have caught the train.', hint: 'leave', answers: ['had left', "'d left"], explain: 'If + Past Perfect: had left.' },
      { kind: 'choice', prompt: "If I hadn't eaten so much, I ___ sick now.", options: ["wouldn't feel", "wouldn't have felt", "didn't feel"], answer: 0, explain: 'Смешанное: прошлое условие, следствие сейчас — would + глагол.' },
      { kind: 'choice', prompt: "I wish I ___ taller.", options: ['am', 'were', 'had been'], answer: 1, explain: 'Сожаление о настоящем: wish + were.' },
      { kind: 'input', prompt: 'I wish I ___ to the party yesterday.', hint: 'go', answers: ['had gone', "'d gone"], explain: 'О прошлом: wish + Past Perfect.' },
      { kind: 'choice', prompt: 'I wish it ___ raining — it’s been raining for days!', options: ['stops', 'would stop', 'stopped'], answer: 1, explain: 'Раздражение, желание перемены — wish + would.' },
      { kind: 'input', prompt: 'We ___ the match if we had played better.', hint: 'win', answers: ['would have won', "'d have won"], explain: 'would have + won.' },
      { kind: 'order', translation: 'Если бы я знал, я бы пришёл.', answer: 'If I had known, I would have come.' },
      { kind: 'input', prompt: "If I ___ the alarm, I wouldn't have been late.", hint: 'hear', answers: ['had heard', "'d heard"], explain: 'If + Past Perfect: had heard.' },
      { kind: 'choice', prompt: "If he ___ so much, he wouldn't feel ill now.", options: ["hadn't eaten", "didn't eat", "wouldn't eat"], answer: 0, explain: 'Смешанное: прошлое условие — Past Perfect.' },
      { kind: 'choice', prompt: 'If only I ___ more careful yesterday!', options: ['was', 'had been', 'would be'], answer: 1, explain: 'Сожаление о прошлом: had been.' },
      { kind: 'order', translation: 'Жаль, что я не учил испанский в школе.', answer: 'I wish I had studied Spanish at school.' },
    ],
  },
  {
    id: 'en-inversion',
    language: 'en',
    level: 'C1',
    title: 'Инверсия для выразительности',
    summary: 'Never have I seen… — обратный порядок слов после отрицательных наречий.',
    theory: [
      {
        text: 'Если предложение начинается с отрицательного или ограничительного выражения, вспомогательный глагол встаёт **перед** подлежащим, как в вопросе. Так звучит торжественнее и эмоциональнее.',
        table: {
          head: ['Начало', 'Пример'],
          rows: [['Never / Rarely / Seldom', 'Never have I seen such a mess.'], ['Not only … but also', 'Not only did he lie, but he also stole.'], ['Hardly … when / No sooner … than', 'Hardly had we arrived when it started to rain.'], ['Only then / Only after', 'Only then did I understand.'], ['Under no circumstances', 'Under no circumstances should you open it.'], ['Little', 'Little did she know…']],
        },
      },
      {
        heading: 'Условия без if',
        text: 'В формальной речи if можно убрать, поставив глагол вперёд: **Had I known** = If I had known; **Should you need** help = If you need help; **Were it** not for you = If it were not for you.',
        examples: [{ text: '**Had I known** about the strike, I would have taken a taxi.', translation: 'Знай я о забастовке, взял бы такси.' }],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Never ___ such a beautiful sunset.', options: ['I have seen', 'have I seen', 'I saw'], answer: 1, explain: 'После Never — инверсия: have I seen.' },
      { kind: 'choice', prompt: 'Not only ___ late, but he also forgot the tickets.', options: ['he was', 'was he', 'did he be'], answer: 1, explain: 'Not only + инверсия: was he.' },
      { kind: 'input', prompt: 'Rarely ___ she complain.', hint: 'вспомогательный глагол', answers: ['does'], explain: 'Present Simple: Rarely does she complain.' },
      { kind: 'choice', prompt: 'Hardly had I sat down ___ the phone rang.', options: ['than', 'when', 'that'], answer: 1, explain: 'Hardly … when; а вот No sooner … than.' },
      { kind: 'choice', prompt: '___ you need any help, call me.', options: ['Should', 'Would', 'Had'], answer: 0, explain: 'Should you need = If you need.' },
      { kind: 'input', prompt: '___ I known, I would have come.', answers: ['had'], explain: 'Had I known = If I had known.' },
      { kind: 'choice', prompt: 'Only after the meeting ___ the truth.', options: ['I realised', 'did I realise', 'I did realise'], answer: 1, explain: 'Only after + инверсия: did I realise.' },
      { kind: 'order', translation: 'Ни при каких обстоятельствах не открывай эту дверь.', answer: 'Under no circumstances should you open this door.' },
      { kind: 'choice', prompt: 'Seldom ___ such talent.', options: ['we see', 'do we see', 'we do see'], answer: 1, explain: 'Seldom + инверсия с do.' },
      { kind: 'choice', prompt: 'No sooner had she left ___ he called.', options: ['when', 'than', 'that'], answer: 1, explain: 'No sooner … than.' },
      { kind: 'input', prompt: '___ it not been for your help, I would have failed.', answers: ['had'], explain: 'Had it not been for = If it hadn’t been for.' },
      { kind: 'order', translation: 'Только тогда я понял правду.', answer: 'Only then did I understand the truth.' },
    ],
  },
  {
    id: 'en-cleft',
    language: 'en',
    level: 'C1',
    title: 'Выделительные конструкции',
    summary: 'It was Anna who… / What I need is…: как поставить акцент.',
    theory: [
      {
        heading: 'It is / was … who / that',
        text: 'Выделяемая часть ставится между **it is / it was** и **who** (о людях) или **that**. По-русски это часто «именно», «как раз».',
        examples: [
          { text: '**It was Anna who** called you.', translation: 'Звонила тебе именно Анна.' },
          { text: "**It's** the noise **that** I can't stand.", translation: 'Чего я не выношу, так это шума.' },
        ],
      },
      {
        heading: 'What … is',
        text: 'Начало с **What** создаёт ожидание, а главное идёт в конце после **is / was**. С действием — **What I did was (to) + глагол**.',
        examples: [
          { text: '**What I need is** a long holiday.', translation: 'Что мне нужно, так это долгий отпуск.' },
          { text: '**What she did was** call the police.', translation: 'Она просто взяла и вызвала полицию.' },
        ],
      },
      {
        heading: 'Другие варианты',
        text: '**All I want is…** («Всё, чего я хочу, —…»), **The thing that worries me is…**, **The reason why… is that…**, **The place where…**',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'It was my brother ___ broke the window.', options: ['which', 'who', 'what'], answer: 1, explain: 'О человеке — who (или that).' },
      { kind: 'choice', prompt: '___ I need is a cup of coffee.', options: ['That', 'What', 'Which'], answer: 1, explain: 'What I need is…' },
      { kind: 'input', prompt: '___ was in Paris that they first met.', answers: ['it'], explain: 'It was in Paris that…' },
      { kind: 'choice', prompt: 'What he did ___ apologise to everyone.', options: ['is', 'was', 'were'], answer: 1, explain: 'Прошлое: What he did was…' },
      { kind: 'input', prompt: '___ I want is a bit of peace and quiet.', hint: 'всё, что', answers: ['all'], explain: 'All I want is…' },
      { kind: 'choice', prompt: "It's not the money ___ matters.", options: ['what', 'that', 'who'], answer: 1, explain: 'О вещи — that.' },
      { kind: 'choice', prompt: 'The reason ___ I called is that I need your help.', options: ['why', 'what', 'because'], answer: 0, explain: 'The reason why…' },
      { kind: 'order', translation: 'Именно Том рассказал мне новости.', answer: 'It was Tom who told me the news.' },
      { kind: 'input', prompt: 'It was in 2010 ___ we moved to Berlin.', answers: ['that'], explain: 'It was … that.' },
      { kind: 'choice', prompt: '___ annoys me is his attitude.', options: ['What', 'It', 'That'], answer: 0, explain: 'What annoys me is…' },
      { kind: 'choice', prompt: "It's you ___ I want to talk to.", options: ['what', 'who', 'which'], answer: 1, explain: 'О человеке — who (или that).' },
      { kind: 'order', translation: 'Что мне нравится, так это его чувство юмора.', answer: 'What I like is his sense of humour.' },
    ],
  },
  {
    id: 'en-participle-clauses',
    language: 'en',
    level: 'C1',
    title: 'Причастные обороты',
    summary: 'Opening the door, she saw… — как сжать два предложения в одно.',
    theory: [
      {
        text: 'Если у двух действий одно подлежащее, одно из них можно превратить в оборот. **-ing** — активное действие одновременно или чуть раньше; **having + V3** — явно раньше; **V3** — пассивное значение.',
        examples: [
          { text: '**Opening** the door, she saw a stranger.', translation: 'Открыв дверь, она увидела незнакомца.' },
          { text: '**Having finished** the report, he went home.', translation: 'Закончив отчёт, он пошёл домой.' },
          { text: '**Written** in 1850, the novel is still popular.', translation: 'Написанный в 1850 году, роман до сих пор популярен.' },
        ],
      },
      {
        heading: 'Осторожно: одно подлежащее',
        text: 'Подлежащее оборота и главного предложения должно совпадать. ✗ *Walking home, the rain started* — получается, что дождь шёл домой. ✓ **Walking home, I got caught in the rain.**',
      },
      {
        heading: 'После существительного',
        text: 'Оборот заменяет придаточное с who / which: the man **sitting** next to me (= who was sitting), the books **left** on the table (= which were left).',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: '___ the letter, she started to cry.', options: ['Read', 'Reading', 'To read'], answer: 1, explain: 'Активное действие одновременно: Reading.' },
      { kind: 'choice', prompt: '___ in 1889, the tower is the symbol of Paris.', options: ['Building', 'Built', 'Having built'], answer: 1, explain: 'Башню построили — пассив: Built.' },
      { kind: 'input', prompt: '___ finished his work, he went to bed.', answers: ['having'], explain: 'Действие явно раньше: Having finished.' },
      { kind: 'choice', prompt: 'The woman ___ to the manager is my aunt.', options: ['talking', 'talked', 'to talk'], answer: 0, explain: '= who is talking.' },
      { kind: 'choice', prompt: 'Most of the goods ___ in this shop are imported.', options: ['selling', 'sold', 'having sold'], answer: 1, explain: '= which are sold — пассив.' },
      { kind: 'choice', prompt: 'Walking to work, ___.', options: ['the rain started', 'I got caught in the rain'], answer: 1, explain: 'Подлежащее должно совпадать: на работу шёл я, а не дождь.' },
      { kind: 'input', prompt: 'Not ___ what to say, I kept silent.', hint: 'know', answers: ['knowing'], explain: 'Отрицание ставится перед причастием: Not knowing.' },
      { kind: 'order', translation: 'Почувствовав усталость, она рано легла спать.', answer: 'Feeling tired, she went to bed early.' },
      { kind: 'choice', prompt: '___ by the noise, she couldn’t sleep.', options: ['Disturbing', 'Disturbed', 'Having disturbed'], answer: 1, explain: 'Её потревожили — пассивное значение: Disturbed.' },
      { kind: 'input', prompt: 'The man ___ in the corner is my boss.', hint: 'stand', answers: ['standing'], explain: '= who is standing.' },
      { kind: 'choice', prompt: '___ lived abroad for years, he speaks three languages.', options: ['Having', 'Being', 'Had'], answer: 0, explain: 'Раньше и долго: Having lived.' },
      { kind: 'order', translation: 'Не зная дороги, мы спросили полицейского.', answer: 'Not knowing the way, we asked a policeman.' },
    ],
  },
  {
    id: 'en-subjunctive',
    language: 'en',
    level: 'C2',
    title: 'Сослагательное наклонение и формальный стиль',
    summary: 'It is vital that he be present; it’s high time we left.',
    theory: [
      {
        heading: 'Subjunctive после требований',
        text: 'После **insist, demand, recommend, suggest, propose** и **it is essential / vital / important that** в формальном английском глагол стоит в начальной форме без -s и без do: **that he be**, **that she leave**, **that it not be**. В британском варианте возможно **should + глагол**.',
        examples: [
          { text: 'It is vital that he **be** present.', translation: 'Крайне важно, чтобы он присутствовал.' },
          { text: 'They insisted that she **not leave** early.', translation: 'Они настояли, чтобы она не уходила рано.' },
          { text: 'I suggest that he **should see** a doctor.', translation: 'Я предлагаю ему обратиться к врачу.' },
        ],
      },
      {
        heading: 'Нереальное прошедшее',
        text: 'После **it’s (high) time, would rather, as if / as though, suppose** прошедшая форма говорит о настоящем: It’s high time we **left**. I’d rather you **didn’t smoke**. He talks as if he **were** the boss.',
      },
      {
        heading: 'Застывшие выражения',
        text: '**God save the King. Be that as it may. Come what may. Suffice it to say… So be it.**',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'The doctor recommended that he ___ smoking.', options: ['stops', 'stop', 'stopped'], answer: 1, explain: 'Subjunctive: начальная форма без -s.' },
      { kind: 'input', prompt: 'It is essential that every member ___ informed.', hint: 'be', answers: ['be', 'should be'], explain: 'that every member be informed.' },
      { kind: 'choice', prompt: 'They demanded that the decision ___ reversed.', options: ['is', 'be', 'was being'], answer: 1, explain: 'После demand — be.' },
      { kind: 'choice', prompt: "It's high time we ___ home.", options: ['go', 'went', 'will go'], answer: 1, explain: 'It’s high time + Past Simple.' },
      { kind: 'choice', prompt: "I'd rather you ___ tell anyone.", options: ["don't", "didn't", "won't"], answer: 1, explain: 'Would rather + другое лицо + прошедшее: didn’t.' },
      { kind: 'input', prompt: 'She insisted that he ___ come.', hint: 'not', answers: ['not'], explain: 'Отрицание в subjunctive — просто not: that he not come.' },
      { kind: 'choice', prompt: '___ it to say, the plan failed.', options: ['Suffice', 'Suffices', 'Sufficing'], answer: 0, explain: 'Застывшее выражение: Suffice it to say.' },
      { kind: 'order', translation: 'Он ведёт себя так, будто он здесь главный.', answer: 'He behaves as if he were in charge here.' },
      { kind: 'choice', prompt: 'I suggest that she ___ a lawyer.', options: ['contacts', 'contact', 'contacted'], answer: 1, explain: 'После suggest that — начальная форма.' },
      { kind: 'choice', prompt: "It's about time you ___ a job.", options: ['get', 'got', 'will get'], answer: 1, explain: 'It’s (about) time + прошедшее.' },
      { kind: 'input', prompt: 'It is important that he ___ on time.', hint: 'be', answers: ['be', 'should be'], explain: 'that he be (или should be).' },
      { kind: 'choice', prompt: "Come what ___, I'll support you.", options: ['may', 'might', 'will'], answer: 0, explain: 'Застывшее выражение: Come what may.' },
    ],
  },
  {
    id: 'en-ellipsis',
    language: 'en',
    level: 'C2',
    title: 'Эллипсис и замещение',
    summary: 'So do I, I hope so, I’d love to: как не повторять уже сказанное.',
    theory: [
      {
        heading: 'Вспомогательный глагол вместо всей фразы',
        text: 'Носители не повторяют глагол целиком: его заменяет вспомогательный. **So + вспом. + подлежащее** — «и я тоже», **Neither / Nor** — «и я тоже не».',
        examples: [
          { text: 'I love jazz. — **So do I.**', translation: 'Я люблю джаз. — Я тоже.' },
          { text: "She can't swim, and **neither can** her brother.", translation: 'Она не умеет плавать, и её брат тоже.' },
          { text: "He said he'd call, but he **didn't**.", translation: 'Он обещал позвонить, но не позвонил.' },
        ],
      },
      {
        heading: 'So / not вместо придаточного',
        text: 'После **think, hope, expect, suppose, be afraid**: I think **so**, I hope **not**, I’m afraid **not**, I don’t think **so**.',
      },
      {
        heading: 'To без глагола и one / ones',
        text: 'Частица **to** заменяет уже названный глагол: I’d love **to**. You don’t have **to**. Существительное заменяют **one / ones**: I don’t like the red shirt — I prefer the blue **one**.',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: "I'm tired. — So ___ I.", options: ['do', 'am', 'have'], answer: 1, explain: 'Повторяем вспомогательный из фразы: am.' },
      { kind: 'choice', prompt: "He didn't like the film, and neither ___ I.", options: ['did', 'didn’t', 'do'], answer: 0, explain: 'Neither + утвердительный вспомогательный: neither did I.' },
      { kind: 'input', prompt: 'Is it going to rain? — I hope ___.', hint: 'надеюсь, что нет', answers: ['not'], explain: 'I hope not.' },
      { kind: 'input', prompt: 'Will you come to the party? — I’d love ___.', answers: ['to'], explain: 'Частица to заменяет come.' },
      { kind: 'choice', prompt: "These shoes are too small. Have you got bigger ___?", options: ['one', 'ones', 'them'], answer: 1, explain: 'Shoes — множественное: ones.' },
      { kind: 'input', prompt: 'She says she can fix it, but I don’t think she ___.', answers: ['can'], explain: 'Вспомогательный can заменяет can fix it.' },
      { kind: 'choice', prompt: "Have you finished? — I'm afraid ___.", options: ['not', 'no', "don't"], answer: 0, explain: 'I’m afraid not.' },
      { kind: 'order', translation: 'Я думал, ты придёшь, но ты не пришёл.', answer: "I thought you would come, but you didn't." },
      { kind: 'choice', prompt: "I can't swim. — Neither ___ I.", options: ['can', "can't", 'do'], answer: 0, explain: 'Neither + утвердительный вспомогательный: neither can I.' },
      { kind: 'input', prompt: 'Will it be ready soon? — I expect ___.', answers: ['so'], explain: 'I expect so.' },
      { kind: 'choice', prompt: 'You can borrow my car if you want ___.', options: ['it', 'to', 'so'], answer: 1, explain: 'To заменяет borrow my car.' },
      { kind: 'choice', prompt: 'Which cake would you like? — The chocolate ___, please.', options: ['one', 'ones', 'it'], answer: 0, explain: 'Один торт — one.' },
    ],
  },
  {
    id: 'en-agreement',
    language: 'en',
    level: 'C2',
    title: 'Согласование: is или are?',
    summary: 'The number of… is, a number of… are, neither… nor: трудные случаи.',
    theory: [
      {
        heading: 'Коварные существительные',
        text: '**News, mathematics, physics, economics** — единственное число, несмотря на -s: The news **is** good. **Police, people, cattle** — всегда множественное: The police **are** here. **Team, family, government** в британском английском могут быть и тем и другим, но с единственным числом не ошибёшься.',
      },
      {
        heading: 'Количество',
        text: '**The number of** + сущ. — речь о самом числе, глагол в единственном: The number of students **is** growing. **A number of** = «несколько» — множественное: A number of students **are** absent. Сумма, расстояние, срок воспринимаются как одно целое: Ten years **is** a long time. Fifty dollars **is** too much.',
        examples: [
          { text: '**The number of** cars **is** increasing.', translation: 'Число машин растёт.' },
          { text: '**A number of** problems **have** appeared.', translation: 'Возник ряд проблем.' },
        ],
      },
      {
        heading: 'Пары, each и one of',
        text: 'С **neither … nor / either … or / not only … but also** глагол согласуется с **ближайшим** подлежащим: Neither the teacher nor the students **were** ready. **Each, every, everybody, nobody** — единственное число. **One of the** + мн. ч. — глагол согласуется с one: One of my friends **lives** in Rome. **None of** формально требует единственного, но в речи обычны оба варианта.',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'The news ___ good today.', options: ['is', 'are'], answer: 0, explain: 'News — единственное число.' },
      { kind: 'choice', prompt: 'The police ___ looking for the thief.', options: ['is', 'are'], answer: 1, explain: 'Police — всегда множественное.' },
      { kind: 'choice', prompt: 'The number of tourists ___ growing every year.', options: ['is', 'are'], answer: 0, explain: 'The number of — речь о числе: is.' },
      { kind: 'choice', prompt: 'A number of students ___ absent today.', options: ['is', 'are'], answer: 1, explain: 'A number of = несколько: are.' },
      { kind: 'choice', prompt: 'Ten kilometres ___ a long way to walk.', options: ['is', 'are'], answer: 0, explain: 'Расстояние как одно целое: is.' },
      { kind: 'choice', prompt: 'Neither my brother nor my parents ___ at home.', options: ['was', 'were'], answer: 1, explain: 'Ближайшее подлежащее — parents: were.' },
      { kind: 'choice', prompt: 'Either the students or the teacher ___ to blame.', options: ['is', 'are'], answer: 0, explain: 'Ближайшее — the teacher: is.' },
      { kind: 'choice', prompt: 'Each of the rooms ___ a balcony.', options: ['has', 'have'], answer: 0, explain: 'Each — единственное число.' },
      { kind: 'choice', prompt: 'One of my friends ___ in Canada.', options: ['live', 'lives'], answer: 1, explain: 'Подлежащее — one: lives.' },
      { kind: 'input', prompt: 'Mathematics ___ my favourite subject.', hint: 'to be', answers: ['is'], explain: 'Mathematics — единственное число.' },
      { kind: 'input', prompt: 'Everybody ___ the answer.', hint: 'know', answers: ['knows'], explain: 'Everybody — единственное число: knows.' },
      { kind: 'order', translation: 'Большинство людей любят музыку.', answer: 'Most people like music.' },
    ],
  },
]
