import type { Lesson } from './types'

export const SPANISH_LESSONS: Lesson[] = [
  {
    id: 'es-ser-estar',
    language: 'es',
    level: 'A1',
    title: 'Ser и estar: два глагола «быть»',
    summary: 'Soy médico, estoy cansado: что постоянно, а что — состояние и место.',
    theory: [
      {
        text: '**Ser** говорит о том, что человек или предмет есть: имя, профессия, происхождение, характер, внешность. **Estar** — о состоянии и о том, где что находится.',
        examples: [
          { text: '**Soy** médico. **Es** de México.', translation: 'Я врач. Он из Мексики.' },
          { text: '**Estoy** cansado. Madrid **está** en España.', translation: 'Я устал. Мадрид находится в Испании.' },
        ],
      },
      {
        heading: 'Спряжение',
        text: 'Оба глагола неправильные — формы нужно запомнить.',
        table: {
          head: ['', 'ser', 'estar'],
          rows: [['yo', 'soy', 'estoy'], ['tú', 'eres', 'estás'], ['él, ella, usted', 'es', 'está'], ['nosotros', 'somos', 'estamos'], ['vosotros', 'sois', 'estáis'], ['ellos, ustedes', 'son', 'están']],
        },
      },
      {
        heading: 'Меняется смысл',
        text: 'С одним и тем же прилагательным ser и estar дают разные значения.',
        examples: [
          { text: 'Juan **es** aburrido.', translation: 'Хуан — скучный человек.' },
          { text: 'Juan **está** aburrido.', translation: 'Хуану скучно.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Yo ___ estudiante.', options: ['soy', 'estoy', 'es'], answer: 0, explain: 'Кто ты по роду занятий — ser: soy estudiante.' },
      { kind: 'choice', prompt: '¿Dónde ___ el baño?', options: ['es', 'está', 'son'], answer: 1, explain: 'Где находится — estar: está.' },
      { kind: 'input', prompt: 'Nosotros ___ muy cansados hoy.', hint: 'estar', answers: ['estamos'], explain: 'Состояние — estar, nosotros estamos.' },
      { kind: 'input', prompt: 'Ellas ___ de Argentina.', hint: 'ser', answers: ['son'], explain: 'Происхождение — ser, ellas son.' },
      { kind: 'choice', prompt: 'La sopa ___ fría, ¡caliéntala!', options: ['es', 'está'], answer: 1, explain: 'Суп остыл — это состояние, estar.' },
      { kind: 'choice', prompt: 'Mi hermano ___ alto y simpático.', options: ['es', 'está'], answer: 0, explain: 'Внешность и характер — ser.' },
      { kind: 'input', prompt: '¿Cómo ___ tú?', hint: 'estar', answers: ['estás'], explain: '«Как дела?» — про состояние: ¿Cómo estás?' },
      { kind: 'order', translation: 'Мадрид находится в центре Испании.', answer: 'Madrid está en el centro de España.' },
      { kind: 'input', prompt: 'Nosotros ___ de Ucrania.', hint: 'ser', answers: ['somos'], explain: 'Происхождение — ser.' },
      { kind: 'choice', prompt: 'La puerta ___ abierta.', options: ['es', 'está'], answer: 1, explain: 'Состояние — estar.' },
      { kind: 'choice', prompt: 'Hoy ___ lunes.', options: ['es', 'está'], answer: 0, explain: 'День недели и дата — ser.' },
      { kind: 'order', translation: 'Мой отец — учитель, но сейчас он в отпуске.', answer: 'Mi padre es profesor, pero ahora está de vacaciones.' },
    ],
  },
  {
    id: 'es-presente',
    language: 'es',
    level: 'A1',
    title: 'Настоящее время: глаголы на -ar, -er, -ir',
    summary: 'Hablo, comes, vivimos: окончания правильных глаголов.',
    theory: [
      {
        text: 'Испанские глаголы делятся на три группы по окончанию: **-ar, -er, -ir**. Окончание отбрасывается, и к основе добавляется окончание лица.',
        table: {
          head: ['', 'hablar', 'comer', 'vivir'],
          rows: [['yo', 'hablo', 'como', 'vivo'], ['tú', 'hablas', 'comes', 'vives'], ['él, ella, usted', 'habla', 'come', 'vive'], ['nosotros', 'hablamos', 'comemos', 'vivimos'], ['vosotros', 'habláis', 'coméis', 'vivís'], ['ellos, ustedes', 'hablan', 'comen', 'viven']],
        },
      },
      {
        heading: 'Местоимение можно опустить',
        text: 'Окончание уже показывает, кто действует, поэтому yo, tú, nosotros обычно не говорят. **Usted** (вежливое «вы») спрягается как él.',
        examples: [
          { text: '**Hablo** español.', translation: 'Я говорю по-испански.' },
          { text: '¿Dónde **vive** usted?', translation: 'Где вы живёте?' },
        ],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Yo ___ inglés y español.', hint: 'hablar', answers: ['hablo'], explain: 'yo → -o: hablo.' },
      { kind: 'input', prompt: '¿Tú ___ en Madrid?', hint: 'vivir', answers: ['vives'], explain: 'tú → -es для глаголов на -ir: vives.' },
      { kind: 'input', prompt: 'Nosotros ___ a las dos.', hint: 'comer', answers: ['comemos'], explain: 'nosotros → -emos: comemos.' },
      { kind: 'choice', prompt: 'Mis padres ___ en un banco.', options: ['trabaja', 'trabajan', 'trabajamos'], answer: 1, explain: 'Mis padres = ellos → trabajan.' },
      { kind: 'choice', prompt: 'Ana ___ muchos libros.', options: ['lee', 'lees', 'leen'], answer: 0, explain: 'Ana = ella → lee.' },
      { kind: 'input', prompt: 'Vosotros ___ muy bien.', hint: 'escribir', answers: ['escribís'], explain: 'vosotros → -ís для глаголов на -ir: escribís.' },
      { kind: 'choice', prompt: '¿Qué ___ usted?', options: ['bebes', 'bebe', 'beben'], answer: 1, explain: 'Usted спрягается как él: bebe.' },
      { kind: 'order', translation: 'Мы живём в маленьком доме.', answer: 'Vivimos en una casa pequeña.' },
      { kind: 'input', prompt: 'Ellos ___ en un restaurante.', hint: 'trabajar', answers: ['trabajan'], explain: 'ellos → -an: trabajan.' },
      { kind: 'input', prompt: 'Yo ___ agua.', hint: 'beber', answers: ['bebo'], explain: 'yo → -o: bebo.' },
      { kind: 'choice', prompt: '¿Vosotros ___ español?', options: ['habláis', 'hablan', 'hablamos'], answer: 0, explain: 'vosotros → -áis: habláis.' },
      { kind: 'choice', prompt: 'Mi hermana ___ cartas a sus amigas.', options: ['escribe', 'escribes', 'escriben'], answer: 0, explain: 'Mi hermana = ella → escribe.' },
    ],
  },
  {
    id: 'es-genero',
    language: 'es',
    level: 'A1',
    title: 'Род существительных и артикли',
    summary: 'El libro, la casa, unos amigos: род, число и согласование.',
    theory: [
      {
        text: 'Существительные на **-o** обычно мужского рода, на **-a** — женского: el libro, la casa. На **-ción, -dad** — всегда женского: la canción, la ciudad. Есть исключения: **el día, el mapa, el problema, la mano, la foto**.',
        table: {
          head: ['', 'мужской', 'женский'],
          rows: [['определённый (тот самый)', 'el / los', 'la / las'], ['неопределённый (какой-то)', 'un / unos', 'una / unas']],
        },
      },
      {
        heading: 'Прилагательное согласуется',
        text: 'Прилагательное принимает род и число существительного и обычно стоит после него.',
        examples: [
          { text: 'el coche **rojo** — la casa **roja**', translation: 'красная машина — красный дом' },
          { text: 'los coches **rojos** — las casas **rojas**', translation: 'красные машины — красные дома' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: '___ casa es grande.', options: ['El', 'La', 'Los'], answer: 1, explain: 'Casa — женский род: la casa.' },
      { kind: 'choice', prompt: '___ problema es serio.', options: ['El', 'La'], answer: 0, explain: 'Problema — исключение, мужской род.' },
      { kind: 'choice', prompt: 'Tengo ___ pregunta.', options: ['un', 'una'], answer: 1, explain: 'Pregunta — женский род: una.' },
      { kind: 'choice', prompt: '___ ciudades son bonitas.', options: ['Los', 'Las'], answer: 1, explain: 'Ciudad на -dad — женский род, мн. ч.: las.' },
      { kind: 'input', prompt: 'Es una canción muy ___.', hint: 'bonito', answers: ['bonita'], explain: 'Canción женского рода → bonita.' },
      { kind: 'choice', prompt: 'Hoy es ___ día perfecto.', options: ['un', 'una'], answer: 0, explain: 'Día — исключение, мужской род: un día.' },
      { kind: 'input', prompt: 'Los coches ___ son rápidos.', hint: 'rojo', answers: ['rojos'], explain: 'Мужской род, мн. ч.: rojos.' },
      { kind: 'order', translation: 'Окна в комнате большие.', answer: 'Las ventanas de la habitación son grandes.' },
      { kind: 'choice', prompt: '___ problema es difícil.', options: ['El', 'La'], answer: 0, explain: 'Problema — мужской род, хотя кончается на -a.' },
      { kind: 'choice', prompt: 'Me duele ___ mano.', options: ['el', 'la'], answer: 1, explain: 'Mano — женский род, хотя кончается на -o.' },
      { kind: 'choice', prompt: '___ ciudades de España son bonitas.', options: ['Los', 'Las'], answer: 1, explain: 'На -dad — женский род: las ciudades.' },
      { kind: 'choice', prompt: 'Las casas son ___.', options: ['blanco', 'blancas', 'blancos'], answer: 1, explain: 'Прилагательное согласуется: женский род, мн. ч.' },
    ],
  },
  {
    id: 'es-gustar',
    language: 'es',
    level: 'A2',
    title: 'Глагол gustar: что мне нравится',
    summary: 'Me gusta el café, me gustan los gatos.',
    theory: [
      {
        text: 'Gustar устроен как русское «мне нравится»: то, что нравится, — подлежащее, а кому — местоимение **me, te, le, nos, os, les**. Если нравится одна вещь или действие — **gusta**, если несколько вещей — **gustan**.',
        examples: [
          { text: 'Me **gusta** el café.', translation: 'Мне нравится кофе.' },
          { text: 'Me **gusta** leer.', translation: 'Мне нравится читать.' },
          { text: 'Me **gustan** los gatos.', translation: 'Мне нравятся кошки.' },
        ],
      },
      {
        heading: 'Кому нравится',
        text: 'Для ясности или выделения добавляют **a + имя или местоимение**. В отрицании no ставится перед местоимением.',
        examples: [
          { text: '**A Ana le** gusta bailar.', translation: 'Ане нравится танцевать.' },
          { text: '**No me** gustan las películas de terror.', translation: 'Мне не нравятся фильмы ужасов.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Me ___ el chocolate.', options: ['gusta', 'gustan', 'gusto'], answer: 0, explain: 'Шоколад — одна вещь: gusta.' },
      { kind: 'choice', prompt: 'Me ___ los gatos.', options: ['gusta', 'gustan'], answer: 1, explain: 'Кошки — несколько: gustan.' },
      { kind: 'choice', prompt: '¿A ti ___ gusta bailar?', options: ['me', 'te', 'le'], answer: 1, explain: 'A ti → te.' },
      { kind: 'input', prompt: 'A nosotros ___ gusta viajar.', hint: 'местоимение', answers: ['nos'], explain: 'A nosotros → nos.' },
      { kind: 'choice', prompt: 'A mis padres ___ gusta el cine.', options: ['les', 'le', 'los'], answer: 0, explain: 'Родители — они: les.' },
      { kind: 'input', prompt: 'No me ___ las películas de terror.', hint: 'gustar', answers: ['gustan'], explain: 'Las películas — мн. ч.: gustan.' },
      { kind: 'choice', prompt: 'A Carlos le ___ jugar al fútbol.', options: ['gusta', 'gustan'], answer: 0, explain: 'Нравится действие (инфинитив) — gusta.' },
      { kind: 'order', translation: 'Тебе нравятся детективы?', answer: '¿Te gustan las novelas de misterio?' },
      { kind: 'choice', prompt: 'A mí me ___ los perros.', options: ['gusta', 'gustan'], answer: 1, explain: 'Los perros — несколько: gustan.' },
      { kind: 'input', prompt: 'A nosotros ___ gusta bailar.', answers: ['nos'], explain: 'Кому? Нам — nos.' },
      { kind: 'choice', prompt: 'A Ana le ___ el chocolate.', options: ['gusta', 'gustan', 'gusto'], answer: 0, explain: 'El chocolate — одна вещь: gusta.' },
      { kind: 'order', translation: 'Тебе нравятся эти туфли?', answer: '¿Te gustan estos zapatos?' },
    ],
  },
  {
    id: 'es-indefinido',
    language: 'es',
    level: 'A2',
    title: 'Pretérito indefinido: законченное прошлое',
    summary: 'Hablé, comiste, fuimos: что произошло и закончилось.',
    theory: [
      {
        text: 'Pretérito indefinido — для действий, которые произошли и закончились в прошлом. Подсказки: **ayer, anoche, el año pasado, en 2019, hace dos días**.',
        table: {
          head: ['', 'hablar', 'comer', 'vivir'],
          rows: [['yo', 'hablé', 'comí', 'viví'], ['tú', 'hablaste', 'comiste', 'viviste'], ['él, ella, usted', 'habló', 'comió', 'vivió'], ['nosotros', 'hablamos', 'comimos', 'vivimos'], ['vosotros', 'hablasteis', 'comisteis', 'vivisteis'], ['ellos, ustedes', 'hablaron', 'comieron', 'vivieron']],
        },
      },
      {
        heading: 'Ударение меняет смысл',
        text: '**hablo** — я говорю, **habló** — он говорил. Знак ударения здесь обязателен.',
      },
      {
        heading: 'Неправильные глаголы',
        text: 'Ser и ir в этом времени совпадают: **fui, fuiste, fue, fuimos, fuisteis, fueron**. Другие частые: tener → **tuve**, estar → **estuve**, hacer → **hice, hizo**.',
        examples: [{ text: 'El verano pasado **fuimos** a Perú.', translation: 'Прошлым летом мы ездили в Перу.' }],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Ayer yo ___ con mi jefe.', hint: 'hablar', answers: ['hablé'], explain: 'yo → -é: hablé.' },
      { kind: 'input', prompt: 'Ella ___ paella el domingo.', hint: 'comer', answers: ['comió'], explain: 'ella → -ió: comió.' },
      { kind: 'choice', prompt: 'El año pasado nosotros ___ a Perú.', options: ['vamos', 'fuimos', 'fueron'], answer: 1, explain: 'Ir в прошлом, nosotros: fuimos.' },
      { kind: 'input', prompt: '¿Qué ___ tú el fin de semana?', hint: 'hacer', answers: ['hiciste'], explain: 'Hacer — неправильный: tú hiciste.' },
      { kind: 'choice', prompt: 'Mis amigos ___ en la playa todo el día.', options: ['estuvieron', 'estuvimos', 'estuve'], answer: 0, explain: 'Mis amigos = ellos: estuvieron.' },
      { kind: 'input', prompt: 'Yo ___ en Sevilla tres años.', hint: 'vivir', answers: ['viví'], explain: 'yo → -í: viví.' },
      { kind: 'choice', prompt: 'Colón ___ a América en 1492.', options: ['llegó', 'llegué', 'llegaron'], answer: 0, explain: 'Colón = él: llegó.' },
      { kind: 'order', translation: 'Вчера вечером мы посмотрели очень хороший фильм.', answer: 'Anoche vimos una película muy buena.' },
      { kind: 'input', prompt: 'Ayer yo ___ con mi madre.', hint: 'hablar', answers: ['hablé'], explain: 'yo → -é: hablé.' },
      { kind: 'input', prompt: 'El año pasado ellos ___ a México.', hint: 'ir', answers: ['fueron'], explain: 'ir → fueron.' },
      { kind: 'choice', prompt: '¿Qué ___ tú anoche?', options: ['hiciste', 'hizo', 'haces'], answer: 0, explain: 'hacer, tú → hiciste.' },
      { kind: 'input', prompt: 'Ella ___ la carta ayer.', hint: 'escribir', answers: ['escribió'], explain: 'ella → -ió: escribió.' },
    ],
  },
  {
    id: 'es-gerundio',
    language: 'es',
    level: 'A2',
    title: 'Estar + gerundio: что происходит сейчас',
    summary: 'Estoy leyendo — действие в процессе.',
    theory: [
      {
        text: 'Чтобы подчеркнуть, что действие идёт прямо сейчас, используют **estar + gerundio**. Герундий образуется так: -ar → **-ando**, -er / -ir → **-iendo**.',
        table: {
          head: ['Глагол', 'Gerundio'],
          rows: [['hablar', 'hablando'], ['comer', 'comiendo'], ['escribir', 'escribiendo'], ['leer', 'leyendo'], ['dormir', 'durmiendo'], ['pedir', 'pidiendo']],
        },
      },
      {
        heading: 'Особые формы',
        text: 'Если основа кончается на гласную, -iendo превращается в **-yendo**: leer → leyendo, oír → oyendo, ir → yendo. У части глаголов на -ir гласная в основе меняется: dormir → **durmiendo**, pedir → **pidiendo**, decir → **diciendo**.',
        examples: [
          { text: '**Estoy leyendo** un libro muy bueno.', translation: 'Я читаю очень хорошую книгу.' },
          { text: '¿Qué **estás haciendo**?', translation: 'Что ты делаешь?' },
          { text: 'Los niños **están durmiendo**.', translation: 'Дети спят.' },
        ],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Ahora mismo ___ con mi madre.', hint: 'estar + hablar, yo', answers: ['estoy hablando'], explain: 'estoy + hablando.' },
      { kind: 'input', prompt: 'Los niños ___ en el jardín.', hint: 'estar + jugar', answers: ['están jugando'], explain: 'están + jugando.' },
      { kind: 'choice', prompt: 'Mi padre está ___ el periódico.', options: ['leiendo', 'leyendo', 'leendo'], answer: 1, explain: 'Основа на гласную: leyendo.' },
      { kind: 'choice', prompt: 'No hagas ruido, el bebé está ___.', options: ['dormiendo', 'durmiendo', 'dormido'], answer: 1, explain: 'dormir → durmiendo (o → u).' },
      { kind: 'input', prompt: '¿Qué ___ tú?', hint: 'estar + hacer', answers: ['estás haciendo'], explain: 'estás + haciendo.' },
      { kind: 'choice', prompt: 'Nosotros ___ comiendo.', options: ['estamos', 'somos', 'están'], answer: 0, explain: 'Процесс — только estar: estamos comiendo.' },
      { kind: 'choice', prompt: 'Ella está ___ una carta.', options: ['escribando', 'escribiendo', 'escribido'], answer: 1, explain: '-ir → -iendo: escribiendo.' },
      { kind: 'order', translation: 'Что ты сейчас читаешь?', answer: '¿Qué estás leyendo ahora?' },
      { kind: 'input', prompt: 'Estamos ___ la cena.', hint: 'preparar', answers: ['preparando'], explain: '-ar → -ando.' },
      { kind: 'choice', prompt: 'Mi madre está ___ un café.', options: ['pidiendo', 'pediendo', 'pedindo'], answer: 0, explain: 'pedir → pidiendo (e → i).' },
      { kind: 'choice', prompt: '¿Qué estás ___? No te oigo.', options: ['diciendo', 'deciendo', 'dicendo'], answer: 0, explain: 'decir → diciendo.' },
      { kind: 'input', prompt: 'Ellos ___ la tele.', hint: 'estar + ver', answers: ['están viendo'], explain: 'están + viendo.' },
    ],
  },
  {
    id: 'es-imperfecto',
    language: 'es',
    level: 'B1',
    title: 'Imperfecto или indefinido',
    summary: 'Llovía, cuando llegué: фон и событие в прошлом.',
    theory: [
      {
        text: '**Pretérito imperfecto** описывает фон, привычки в прошлом и то, «как было». Окончания: -ar → **-aba**, -er / -ir → **-ía**. Неправильных всего три: **ser** (era), **ir** (iba), **ver** (veía).',
        table: {
          head: ['', 'hablar', 'vivir', 'ser', 'ir'],
          rows: [['yo', 'hablaba', 'vivía', 'era', 'iba'], ['tú', 'hablabas', 'vivías', 'eras', 'ibas'], ['él, ella', 'hablaba', 'vivía', 'era', 'iba'], ['nosotros', 'hablábamos', 'vivíamos', 'éramos', 'íbamos'], ['ellos', 'hablaban', 'vivían', 'eran', 'iban']],
        },
      },
      {
        heading: 'Фон и событие',
        text: 'Imperfecto — что происходило, обстановка, описание (**llovía, era tarde, estaba cansado**). Indefinido — что случилось, законченное действие (**llegué, me llamó**). Подсказки imperfecto: **antes, siempre, de niño, todos los días, mientras**.',
        examples: [
          { text: '**Llovía** cuando **llegué** a casa.', translation: 'Когда я пришёл домой, шёл дождь.' },
          { text: 'De niño **vivía** en un pueblo.', translation: 'В детстве я жил в деревне.' },
          { text: 'Ayer **vi** a Marta: **estaba** muy contenta.', translation: 'Вчера я видел Марту: она была очень довольна.' },
        ],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Cuando era pequeño, ___ en Sevilla.', hint: 'vivir, yo', answers: ['vivía'], explain: 'Обстановка в детстве — imperfecto: vivía.' },
      { kind: 'choice', prompt: 'Mientras yo cocinaba, ___ el teléfono.', options: ['sonaba', 'sonó', 'suena'], answer: 1, explain: 'Звонок — событие на фоне: sonó.' },
      { kind: 'input', prompt: 'Todos los veranos ___ a la playa.', hint: 'ir, nosotros', answers: ['íbamos'], explain: 'Привычка в прошлом: íbamos.' },
      { kind: 'choice', prompt: 'Ayer ___ las nueve cuando salí de casa.', options: ['fueron', 'eran', 'son'], answer: 1, explain: 'Время как фон — imperfecto: eran las nueve.' },
      { kind: 'choice', prompt: 'El año pasado ___ a Perú.', options: ['viajé', 'viajaba', 'viajo'], answer: 0, explain: 'Законченное действие в определённый период — indefinido.' },
      { kind: 'input', prompt: 'La casa ___ grande y tenía un jardín.', hint: 'ser', answers: ['era'], explain: 'Описание — imperfecto: era.' },
      { kind: 'choice', prompt: 'Estaba durmiendo cuando ___.', options: ['llamabas', 'llamaste', 'llamas'], answer: 1, explain: 'Звонок прервал сон — indefinido.' },
      { kind: 'order', translation: 'Когда я был ребёнком, я много читал.', answer: 'Cuando era niño, leía mucho.' },
      { kind: 'input', prompt: 'Antes mi abuelo ___ mucho.', hint: 'trabajar', answers: ['trabajaba'], explain: 'Привычка в прошлом: trabajaba.' },
      { kind: 'choice', prompt: 'Cuando ___ niños, veíamos dibujos todas las mañanas.', options: ['éramos', 'fuimos', 'somos'], answer: 0, explain: 'Описание детства — imperfecto: éramos.' },
      { kind: 'choice', prompt: 'Ayer ___ al médico.', options: ['iba', 'fui', 'voy'], answer: 1, explain: 'Законченное действие вчера — indefinido.' },
      { kind: 'order', translation: 'Когда я пришёл, они ужинали.', answer: 'Cuando llegué, cenaban.' },
    ],
  },
  {
    id: 'es-pronombres',
    language: 'es',
    level: 'B1',
    title: 'Местоимения-дополнения: lo, la, le, se lo',
    summary: 'Te lo doy, se lo digo: кому и что.',
    theory: [
      {
        text: 'Прямое дополнение (кого? что?) — **lo, la, los, las**. Косвенное (кому?) — **le, les**. Для я, ты, мы, вы формы общие: **me, te, nos, os**. Местоимение стоит перед спрягаемым глаголом.',
        examples: [
          { text: '¿El libro? **Lo** tengo yo.', translation: 'Книга? Она у меня.' },
          { text: '**Le** escribo a mi madre.', translation: 'Я пишу маме.' },
        ],
      },
      {
        heading: 'Два местоимения подряд',
        text: 'Сначала «кому», потом «что»: **me lo, te la**. Если встречаются le / les + lo / la, то le превращается в **se**: не «le lo», а **se lo**.',
        examples: [
          { text: '**Te lo** explico.', translation: 'Я тебе это объясню.' },
          { text: '¿Le das el regalo a Ana? — Sí, **se lo** doy.', translation: 'Ты даришь Ане подарок? — Да, дарю.' },
        ],
      },
      {
        heading: 'С инфинитивом, герундием и приказом',
        text: 'Местоимения можно присоединить к концу: **voy a comprarlo**, **estoy leyéndolo**, а в утвердительном приказе — обязательно: **¡Dímelo!** (ударение сохраняется значком).',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: '¿Dónde está la llave? — No ___ encuentro.', options: ['lo', 'la', 'le'], answer: 1, explain: 'La llave — женский род: la.' },
      { kind: 'choice', prompt: '___ escribí un correo a mis padres.', options: ['Los', 'Les', 'Las'], answer: 1, explain: 'Кому? — косвенное, мн. ч.: les.' },
      { kind: 'input', prompt: '¿Me prestas el coche? — Sí, te ___ presto.', answers: ['lo'], explain: 'El coche — lo: te lo presto.' },
      { kind: 'choice', prompt: '¿Le diste el libro a Juan? — Sí, ___ di.', options: ['le lo', 'se lo', 'lo le'], answer: 1, explain: 'le + lo → se lo.' },
      { kind: 'input', prompt: 'Las entradas: voy a ___ mañana.', hint: 'comprar + las', answers: ['comprarlas'], explain: 'Присоединяется к инфинитиву: comprarlas.' },
      { kind: 'choice', prompt: '¡___ la verdad! (decir + me)', options: ['Dime', 'Me di', 'Díme'], answer: 0, explain: 'Утвердительный приказ: Dime (одно местоимение — без значка).' },
      { kind: 'choice', prompt: 'Las flores, ¿___ compraste para mí?', options: ['las', 'los', 'les'], answer: 0, explain: 'Las flores — las.' },
      { kind: 'order', translation: 'Я тебе это завтра объясню.', answer: 'Te lo explico mañana.' },
      { kind: 'choice', prompt: '¿Ves a María? — Sí, ___ veo.', options: ['la', 'le', 'lo'], answer: 0, explain: 'Кого? María — la.' },
      { kind: 'input', prompt: '¿Me compras un helado? — Sí, te ___ compro.', answers: ['lo'], explain: 'Un helado — lo.' },
      { kind: 'choice', prompt: '¿Le has dado las llaves? — Sí, ya ___ he dado.', options: ['se las', 'le las', 'se los'], answer: 0, explain: 'le + las → se las.' },
      { kind: 'input', prompt: 'El libro, ¡___, por favor!', hint: 'dar + me + lo', answers: ['dámelo'], explain: 'Приказ + me + lo, ударение сохраняется: dámelo.' },
    ],
  },
  {
    id: 'es-subjuntivo',
    language: 'es',
    level: 'B1',
    title: 'Presente de subjuntivo: желания и просьбы',
    summary: 'Quiero que vengas: когда хотят, чтобы действовал другой.',
    theory: [
      {
        text: 'Subjuntivo нужен, когда один человек хочет, просит, советует, чтобы **другой** что-то сделал: **querer que, esperar que, pedir que, es importante que**. Если субъект один — просто инфинитив: Quiero **venir**, но Quiero que **vengas**.',
        examples: [
          { text: 'Quiero que **vengas** a mi fiesta.', translation: 'Я хочу, чтобы ты пришёл ко мне на праздник.' },
          { text: 'Espero que **estés** bien.', translation: 'Надеюсь, у тебя всё хорошо.' },
        ],
      },
      {
        heading: 'Как образовать',
        text: 'Берётся форма yo в настоящем, -o отбрасывается и ставятся «чужие» окончания: у -ar — на **-e**, у -er / -ir — на **-a**. Tener → teng-o → **tenga**, hacer → **haga**, venir → **venga**. Свои формы у **ser (sea), ir (vaya), estar (esté), saber (sepa), haber (haya), dar (dé)**.',
        table: {
          head: ['', 'hablar', 'comer', 'tener'],
          rows: [['yo', 'hable', 'coma', 'tenga'], ['tú', 'hables', 'comas', 'tengas'], ['él, ella', 'hable', 'coma', 'tenga'], ['nosotros', 'hablemos', 'comamos', 'tengamos'], ['ellos', 'hablen', 'coman', 'tengan']],
        },
      },
      {
        heading: 'Пожелания',
        text: 'После **ojalá** и в пожеланиях с **que**: ¡Ojalá **haga** sol! ¡Que **tengas** buen viaje!',
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Quiero que tú ___ conmigo.', hint: 'venir', answers: ['vengas'], explain: 'venir → vengo → vengas.' },
      { kind: 'choice', prompt: 'Mis padres quieren que yo ___ medicina.', options: ['estudio', 'estudie', 'estudiar'], answer: 1, explain: 'Разные субъекты: que + subjuntivo.' },
      { kind: 'choice', prompt: 'Quiero ___ medicina.', options: ['estudie', 'estudiar', 'que estudie'], answer: 1, explain: 'Субъект тот же — инфинитив.' },
      { kind: 'input', prompt: 'Espero que ___ un buen día.', hint: 'tener, tú', answers: ['tengas'], explain: 'tener → tengas.' },
      { kind: 'choice', prompt: 'Es importante que todos ___ puntuales.', options: ['son', 'sean', 'están'], answer: 1, explain: 'ser → sean.' },
      { kind: 'input', prompt: '¡Ojalá no ___ mañana!', hint: 'llover', answers: ['llueva'], explain: 'llover → llueva.' },
      { kind: 'choice', prompt: 'Te pido que me ___ la verdad.', options: ['dices', 'digas', 'decir'], answer: 1, explain: 'decir → digo → digas.' },
      { kind: 'order', translation: 'Надеюсь, тебе понравится подарок.', answer: 'Espero que te guste el regalo.' },
      { kind: 'input', prompt: 'Es necesario que vosotros ___ más.', hint: 'estudiar', answers: ['estudiéis'], explain: 'vosotros: estudiéis.' },
      { kind: 'choice', prompt: 'Ojalá ___ buen tiempo mañana.', options: ['hace', 'haga', 'hacer'], answer: 1, explain: 'После ojalá — subjuntivo: haga.' },
      { kind: 'input', prompt: 'Mi jefe quiere que yo ___ el informe hoy.', hint: 'terminar', answers: ['termine'], explain: 'terminar → termine.' },
      { kind: 'choice', prompt: 'Espero ___ pronto.', options: ['verte', 'que te vea', 'que te veo'], answer: 0, explain: 'Надеюсь я и увижу я — один субъект, инфинитив.' },
    ],
  },
  {
    id: 'es-por-para',
    language: 'es',
    level: 'B2',
    title: 'Por и para',
    summary: 'Для кого, ради чего, через что и почему.',
    theory: [
      {
        heading: 'Para — цель и направление',
        text: '**Para** смотрит вперёд: цель (**para aprender**), получатель (**para ti**), пункт назначения (**salgo para Madrid**), срок (**para el lunes**), мнение (**para mí**).',
        examples: [
          { text: 'Este regalo es **para** ti.', translation: 'Этот подарок для тебя.' },
          { text: 'Estudio **para** encontrar un buen trabajo.', translation: 'Я учусь, чтобы найти хорошую работу.' },
        ],
      },
      {
        heading: 'Por — причина и путь',
        text: '**Por** объясняет «из-за чего» и «через что»: причина (**por la lluvia**), место движения (**paseamos por el parque**), время суток (**por la mañana**), средство (**por teléfono**), обмен и цена (**lo compré por 10 euros**), «вместо» (**trabajo por ti**), исполнитель в пассиве (**escrito por Cervantes**).',
        examples: [
          { text: 'Gracias **por** tu ayuda.', translation: 'Спасибо за помощь.' },
          { text: 'No salimos **por** el frío.', translation: 'Мы не вышли из-за холода.' },
        ],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Este libro es ___ mi hermana.', options: ['por', 'para'], answer: 1, explain: 'Получатель — para.' },
      { kind: 'choice', prompt: 'Gracias ___ todo.', options: ['por', 'para'], answer: 0, explain: 'Благодарность за что-то — por.' },
      { kind: 'choice', prompt: 'Caminamos ___ la playa.', options: ['por', 'para'], answer: 0, explain: 'Движение по месту — por.' },
      { kind: 'choice', prompt: 'Necesito el informe ___ el viernes.', options: ['por', 'para'], answer: 1, explain: 'Срок — para.' },
      { kind: 'choice', prompt: 'Lo compré ___ veinte euros.', options: ['por', 'para'], answer: 0, explain: 'Цена, обмен — por.' },
      { kind: 'choice', prompt: 'Ahorro dinero ___ viajar.', options: ['por', 'para'], answer: 1, explain: 'Цель — para.' },
      { kind: 'choice', prompt: 'No fuimos ___ la lluvia.', options: ['por', 'para'], answer: 0, explain: 'Причина — por.' },
      { kind: 'order', translation: 'Для меня это очень важно.', answer: 'Para mí es muy importante.' },
      { kind: 'choice', prompt: 'Te llamo ___ teléfono.', options: ['por', 'para'], answer: 0, explain: 'Средство — por.' },
      { kind: 'choice', prompt: 'Salgo ___ Barcelona mañana.', options: ['por', 'para'], answer: 1, explain: 'Пункт назначения — para.' },
      { kind: 'choice', prompt: '___ la mañana voy al gimnasio.', options: ['Por', 'Para'], answer: 0, explain: 'Время суток — por.' },
      { kind: 'choice', prompt: 'El Quijote fue escrito ___ Cervantes.', options: ['por', 'para'], answer: 0, explain: 'Исполнитель в пассиве — por.' },
    ],
  },
  {
    id: 'es-si-imperfecto',
    language: 'es',
    level: 'B2',
    title: 'Si tuviera…: нереальное условие',
    summary: 'Imperfecto de subjuntivo и condicional.',
    theory: [
      {
        text: 'Воображаемое условие в настоящем: **si + imperfecto de subjuntivo, condicional**. Подобно английскому If I had…, I would…',
        examples: [
          { text: 'Si **tuviera** dinero, **viajaría** por el mundo.', translation: 'Если бы у меня были деньги, я бы путешествовал по миру.' },
          { text: 'Si **fuera** tú, no lo **haría**.', translation: 'На твоём месте я бы этого не делал.' },
        ],
      },
      {
        heading: 'Imperfecto de subjuntivo',
        text: 'Берётся форма ellos в indefinido, -ron отбрасывается и добавляется **-ra**: tuvieron → **tuviera**, fueron → **fuera**, hablaron → **hablara**, pudieron → **pudiera**. Форма nosotros с ударением: **tuviéramos**.',
      },
      {
        heading: 'Condicional',
        text: 'Инфинитив + **-ía, -ías, -ía, -íamos, -íais, -ían**: viajaría, comería. Неправильные основы как в будущем: **tendr-, har-, podr-, dir-, saldr-, vendr-, querr-, sabr-**.',
        examples: [{ text: 'Si **pudiera**, te lo **diría**.', translation: 'Если бы мог, я бы тебе сказал.' }],
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Si ___ más tiempo, aprendería chino.', hint: 'tener, yo', answers: ['tuviera', 'tuviese'], explain: 'tuvieron → tuviera.' },
      { kind: 'input', prompt: 'Si fuera rico, ___ una casa en la playa.', hint: 'comprar, yo', answers: ['compraría'], explain: 'Condicional: compraría.' },
      { kind: 'choice', prompt: 'Si yo ___ tú, aceptaría el trabajo.', options: ['soy', 'fuera', 'sería'], answer: 1, explain: 'Si + imperfecto de subjuntivo: fuera.' },
      { kind: 'choice', prompt: 'Si pudiéramos, ___ contigo.', options: ['iremos', 'iríamos', 'vamos'], answer: 1, explain: 'Condicional: iríamos.' },
      { kind: 'input', prompt: 'Si ___ aquí, te ayudaría.', hint: 'estar, yo', answers: ['estuviera', 'estuviese'], explain: 'estuvieron → estuviera.' },
      { kind: 'choice', prompt: 'Si tuviera hambre, ___ algo.', options: ['comería', 'comiera', 'como'], answer: 0, explain: 'Результат — condicional.' },
      { kind: 'input', prompt: '¿Qué ___ tú en mi lugar?', hint: 'hacer, condicional', answers: ['harías'], explain: 'hacer → har- → harías.' },
      { kind: 'order', translation: 'Если бы я знал испанский, я бы жил в Мадриде.', answer: 'Si supiera español, viviría en Madrid.' },
      { kind: 'input', prompt: 'Si ___ tiempo, iría contigo.', hint: 'tener, yo', answers: ['tuviera', 'tuviese'], explain: 'tener → tuviera.' },
      { kind: 'choice', prompt: 'Si no ___ tan tarde, te llamaría.', options: ['es', 'fuera', 'sería'], answer: 1, explain: 'Si + imperfecto de subjuntivo: fuera.' },
      { kind: 'input', prompt: 'Si viviera en España, ___ español todos los días.', hint: 'hablar, yo', answers: ['hablaría'], explain: 'Condicional: hablaría.' },
      { kind: 'choice', prompt: 'Si ___ tu número, te escribiría.', options: ['sabía', 'supiera', 'sabría'], answer: 1, explain: 'saber → supieron → supiera.' },
    ],
  },
  {
    id: 'es-cuando',
    language: 'es',
    level: 'B2',
    title: 'Cuando + subjuntivo: будущее в придаточном',
    summary: 'Cuando llegues, llámame: время, которое ещё не наступило.',
    theory: [
      {
        text: 'После **cuando, en cuanto, hasta que, tan pronto como, antes de que, después de que** о будущем говорят в **subjuntivo**, а не в будущем времени.',
        examples: [
          { text: 'Cuando **llegues**, llámame.', translation: 'Когда приедешь, позвони мне.' },
          { text: 'Te espero hasta que **termines**.', translation: 'Я подожду, пока ты не закончишь.' },
        ],
      },
      {
        heading: 'А если о привычке или прошлом',
        text: 'Если речь о том, что бывает обычно или уже было, — индикатив: Cuando **llego** a casa, ceno (всегда). Cuando **llegué**, cené (вчера).',
      },
      {
        heading: 'Antes de que — всегда subjuntivo',
        text: '**Antes de que** требует subjuntivo в любом времени, а при одном субъекте заменяется на **antes de + инфинитив**: Salgo antes de que **llueva**. Me lavo las manos antes de **comer**.',
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Cuando ___ a Madrid, te llamaré.', hint: 'llegar, yo', answers: ['llegue'], explain: 'Будущее после cuando — subjuntivo: llegue.' },
      { kind: 'choice', prompt: 'Cuando ___ niño, jugaba al fútbol.', options: ['sea', 'era', 'fuera'], answer: 1, explain: 'Прошлое — индикатив.' },
      { kind: 'choice', prompt: 'Siempre ceno cuando ___ a casa.', options: ['llego', 'llegue', 'llegaré'], answer: 0, explain: 'Привычка — индикатив.' },
      { kind: 'input', prompt: 'Espera aquí hasta que yo ___.', hint: 'volver', answers: ['vuelva'], explain: 'volver → vuelva.' },
      { kind: 'choice', prompt: 'Vámonos antes de que ___.', options: ['llueve', 'llueva', 'lloverá'], answer: 1, explain: 'Antes de que — всегда subjuntivo.' },
      { kind: 'choice', prompt: 'En cuanto ___ el dinero, te lo devuelvo.', options: ['tengo', 'tenga', 'tendré'], answer: 1, explain: 'Будущее после en cuanto — tenga.' },
      { kind: 'input', prompt: 'Lávate las manos antes de ___.', hint: 'comer', answers: ['comer'], explain: 'Субъект тот же — инфинитив.' },
      { kind: 'order', translation: 'Когда закончишь, напиши мне.', answer: 'Cuando termines, escríbeme.' },
      { kind: 'choice', prompt: 'Cuando ___ mayor, quiero ser piloto.', options: ['soy', 'sea', 'seré'], answer: 1, explain: 'Будущее после cuando — subjuntivo.' },
      { kind: 'input', prompt: 'Te lo diré en cuanto lo ___.', hint: 'saber, yo', answers: ['sepa'], explain: 'saber → sepa.' },
      { kind: 'choice', prompt: 'Ayer, cuando ___ a casa, cené.', options: ['llegue', 'llegué', 'llegaré'], answer: 1, explain: 'Прошлое — индикатив.' },
      { kind: 'input', prompt: 'No me iré hasta que tú me lo ___.', hint: 'explicar', answers: ['expliques'], explain: 'explicar → expliques (c → qu).' },
    ],
  },
  {
    id: 'es-pluscuamperfecto',
    language: 'es',
    level: 'C1',
    title: 'Si hubiera sabido…: нереальное прошлое',
    summary: 'Pluscuamperfecto de subjuntivo и condicional compuesto.',
    theory: [
      {
        text: 'Сожаление о прошлом, которое уже не изменить: **si + hubiera + participio, habría + participio**.',
        examples: [
          { text: 'Si lo **hubiera sabido**, **habría venido**.', translation: 'Если бы я знал, я бы пришёл.' },
          { text: 'Si **hubieras estudiado**, **habrías aprobado**.', translation: 'Если бы ты учился, ты бы сдал.' },
        ],
      },
      {
        heading: 'Смешанные условия',
        text: 'Прошлое условие — последствие сейчас: **si + hubiera + participio, condicional simple**. Si **hubiera aceptado** aquel trabajo, ahora **viviría** en Londres.',
      },
      {
        heading: 'Другие случаи',
        text: 'После **ojalá** — сожаление о прошлом: ¡Ojalá **hubiera ido**! После глаголов в прошлом с que: Me alegré de que **hubieras venido**. В разговорной речи вместо habría часто говорят **hubiera**: Si lo hubiera sabido, **hubiera venido**.',
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'Si ___ antes, habríamos llegado a tiempo.', hint: 'salir, nosotros', answers: ['hubiéramos salido', 'hubiésemos salido'], explain: 'hubiéramos + salido.' },
      { kind: 'choice', prompt: 'Si me hubieras llamado, te ___.', options: ['ayudaría', 'habría ayudado', 'ayudé'], answer: 1, explain: 'Прошлое следствие — habría + participio.' },
      { kind: 'choice', prompt: 'Si hubiera estudiado medicina, ahora ___ médico.', options: ['sería', 'habría sido', 'fuera'], answer: 0, explain: 'Смешанное: последствие сейчас — sería.' },
      { kind: 'input', prompt: '¡Ojalá no lo ___!', hint: 'decir, yo, прошлое', answers: ['hubiera dicho', 'hubiese dicho'], explain: 'Сожаление о прошлом: hubiera dicho.' },
      { kind: 'choice', prompt: 'Si ___ el mapa, no nos habríamos perdido.', options: ['tuviéramos', 'hubiéramos traído', 'traemos'], answer: 1, explain: 'Условие в прошлом: hubiéramos traído.' },
      { kind: 'input', prompt: 'Si hubieras venido, te ___.', hint: 'divertir, condicional compuesto', answers: ['habrías divertido'], explain: 'habrías + divertido.' },
      { kind: 'choice', prompt: 'Me molestó que no me ___.', options: ['avisas', 'hubieras avisado', 'habrías avisado'], answer: 1, explain: 'После que в прошлом — hubieras avisado.' },
      { kind: 'order', translation: 'Если бы я знал, я бы тебе сказал.', answer: 'Si lo hubiera sabido, te lo habría dicho.' },
      { kind: 'choice', prompt: 'Si hubieras llegado antes, ___ el principio.', options: ['habrías visto', 'verías', 'vieras'], answer: 0, explain: 'Прошлое следствие — habrías visto.' },
      { kind: 'input', prompt: 'Si no ___ tanto, no estaría cansado.', hint: 'trabajar, yo', answers: ['hubiera trabajado', 'hubiese trabajado'], explain: 'Прошлое условие: hubiera trabajado.' },
      { kind: 'choice', prompt: 'Ojalá ___ a la fiesta ayer.', options: ['vinieras', 'hubieras venido', 'vengas'], answer: 1, explain: 'Сожаление о прошлом: hubieras venido.' },
      { kind: 'order', translation: 'Если бы ты мне позвонил, я бы тебе помог.', answer: 'Si me hubieras llamado, te habría ayudado.' },
    ],
  },
  {
    id: 'es-estilo-indirecto',
    language: 'es',
    level: 'C1',
    title: 'Estilo indirecto: пересказ',
    summary: 'Dijo que estaba cansada: как передать чужие слова.',
    theory: [
      {
        text: 'После **dijo que, comentó que, explicó que** время сдвигается в прошлое, если пересказываем позже.',
        table: {
          head: ['Прямая речь', 'Косвенная речь'],
          rows: [['«Estoy cansada.»', 'Dijo que estaba cansada.'], ['«He terminado.»', 'Dijo que había terminado.'], ['«Fui al cine.»', 'Dijo que había ido al cine.'], ['«Iré mañana.»', 'Dijo que iría al día siguiente.'], ['«Ven.»', 'Me dijo que fuera.']],
        },
      },
      {
        heading: 'Просьбы и вопросы',
        text: 'Приказ или просьба переходит в **imperfecto de subjuntivo**: Me pidió que **cerrara** la puerta. Вопрос «да / нет» вводится **si**, остальные — вопросительным словом со значком: Me preguntó **si** tenía hambre; Me preguntó **dónde** vivía.',
      },
      {
        heading: 'Слова времени и места',
        text: 'hoy → **aquel día**, mañana → **al día siguiente**, ayer → **el día anterior**, aquí → **allí**, este → **aquel**. Venir часто меняется на **ir**, traer — на **llevar**.',
      },
    ],
    exercises: [
      { kind: 'input', prompt: '«Tengo frío.» → Dijo que ___ frío.', answers: ['tenía'], explain: 'Presente → imperfecto: tenía.' },
      { kind: 'choice', prompt: '«He perdido las llaves.» → Dijo que ___ las llaves.', options: ['ha perdido', 'había perdido', 'perdía'], answer: 1, explain: 'Perfecto → pluscuamperfecto.' },
      { kind: 'input', prompt: '«Llegaré tarde.» → Dijo que ___ tarde.', answers: ['llegaría'], explain: 'Futuro → condicional.' },
      { kind: 'choice', prompt: '«Cierra la ventana.» → Me pidió que ___ la ventana.', options: ['cierro', 'cerrara', 'cerraba'], answer: 1, explain: 'Приказ в прошлом — imperfecto de subjuntivo.' },
      { kind: 'choice', prompt: '«¿Tienes hambre?» → Me preguntó ___ tenía hambre.', options: ['que', 'si', 'qué'], answer: 1, explain: 'Вопрос «да / нет» — si.' },
      { kind: 'choice', prompt: '«Vuelvo mañana.» → Dijo que volvía ___.', options: ['mañana', 'al día siguiente', 'ayer'], answer: 1, explain: 'mañana → al día siguiente.' },
      { kind: 'input', prompt: '«¿Dónde vives?» → Me preguntó dónde ___.', answers: ['vivía'], explain: 'Время сдвигается: vivía.' },
      { kind: 'order', translation: 'Она сказала, что придёт на следующий день.', answer: 'Dijo que vendría al día siguiente.' },
      { kind: 'input', prompt: '«Estoy en casa.» → Dijo que ___ en casa.', answers: ['estaba'], explain: 'Presente → imperfecto: estaba.' },
      { kind: 'choice', prompt: '«Haz los deberes.» → Mi madre me dijo que ___ los deberes.', options: ['hago', 'hiciera', 'hacía'], answer: 1, explain: 'Приказ — imperfecto de subjuntivo.' },
      { kind: 'choice', prompt: '«Vine ayer.» → Dijo que había venido ___.', options: ['ayer', 'el día anterior', 'mañana'], answer: 1, explain: 'ayer → el día anterior.' },
      { kind: 'input', prompt: '«¿Cuándo vuelves?» → Me preguntó cuándo ___.', answers: ['volvía'], explain: 'Время сдвигается: volvía.' },
    ],
  },
  {
    id: 'es-se',
    language: 'es',
    level: 'C1',
    title: 'Se: безличные и пассивные предложения',
    summary: 'Se habla español, se venden pisos, se me olvidó.',
    theory: [
      {
        heading: 'Se impersonal',
        text: 'Когда действует «кто-то вообще», без конкретного лица: **se + глагол в 3-м лице ед. ч.** Se vive bien aquí. ¿Cómo **se dice** esto en español?',
      },
      {
        heading: 'Pasiva refleja',
        text: 'Если есть предмет действия, глагол согласуется с ним: **se vende** piso, **se venden** pisos. Такая конструкция гораздо употребительнее, чем пассив с ser.',
        examples: [
          { text: 'Aquí **se habla** español.', translation: 'Здесь говорят по-испански.' },
          { text: '**Se buscan** camareros.', translation: 'Требуются официанты.' },
        ],
      },
      {
        heading: 'Se для случайности',
        text: '**se + me / te / le + глагол**: действие произошло «само», без умысла. Глагол согласуется с вещью: **Se me olvidó** la llave; **se me olvidaron** las llaves; **se le rompió** el vaso.',
        examples: [{ text: '**Se nos acabó** la leche.', translation: 'У нас закончилось молоко.' }],
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'En esta tienda se ___ libros usados.', options: ['vende', 'venden', 'vendemos'], answer: 1, explain: 'Libros — мн. ч.: se venden.' },
      { kind: 'choice', prompt: '¿Cómo se ___ «gracias» en ruso?', options: ['dice', 'dicen', 'dices'], answer: 0, explain: 'Одно слово: se dice.' },
      { kind: 'input', prompt: 'Se ___ piso en el centro.', hint: 'alquilar', answers: ['alquila'], explain: 'Piso — ед. ч.: se alquila.' },
      { kind: 'choice', prompt: 'Lo siento, se me ___ las llaves en casa.', options: ['olvidó', 'olvidaron', 'olvidé'], answer: 1, explain: 'Согласуется с las llaves: olvidaron.' },
      { kind: 'input', prompt: 'A Pedro se ___ rompió el móvil.', answers: ['le'], explain: 'С кем случилось — le: se le rompió.' },
      { kind: 'choice', prompt: 'En España se ___ muy tarde.', options: ['cena', 'cenan', 'cenamos'], answer: 0, explain: 'Безличное se — 3-е лицо ед. ч.' },
      { kind: 'choice', prompt: '___ prohíbe fumar.', options: ['Se', 'Le', 'Lo'], answer: 0, explain: 'Безличное предписание: Se prohíbe.' },
      { kind: 'order', translation: 'У меня упал телефон.', answer: 'Se me cayó el teléfono.' },
      { kind: 'choice', prompt: 'Se ___ camareros.', options: ['busca', 'buscan'], answer: 1, explain: 'Camareros — мн. ч.: se buscan.' },
      { kind: 'input', prompt: 'Ayer se me ___ el móvil.', hint: 'romper', answers: ['rompió'], explain: 'Согласуется с el móvil: rompió.' },
      { kind: 'choice', prompt: '¿Se ___ pagar con tarjeta?', options: ['puede', 'pueden'], answer: 0, explain: 'Безличное: se puede + инфинитив.' },
      { kind: 'order', translation: 'Здесь хорошо кормят.', answer: 'Aquí se come bien.' },
    ],
  },
  {
    id: 'es-concesivas',
    language: 'es',
    level: 'C2',
    title: 'Уступительные предложения: aunque',
    summary: 'Aunque llueve или aunque llueva — разница в одной букве.',
    theory: [
      {
        text: 'После **aunque** выбор наклонения меняет смысл. **Индикатив** — факт, который говорящий признаёт: Aunque **llueve**, salimos (дождь идёт, но мы выходим). **Subjuntivo** — возможность или неважный для говорящего факт: Aunque **llueva**, saldremos (даже если пойдёт дождь).',
        examples: [
          { text: 'Aunque **es** caro, lo compro.', translation: 'Хоть это и дорого, я покупаю.' },
          { text: 'Aunque **sea** caro, lo compraré.', translation: 'Даже если это дорого, я куплю.' },
          { text: 'Aunque **fuera** millonario, no lo haría.', translation: 'Даже будь я миллионером, я бы этого не сделал.' },
        ],
      },
      {
        heading: 'Другие уступительные связки',
        text: '**A pesar de que** и **por más que** ведут себя как aunque. **Por mucho que / por muy + прилагательное + que** почти всегда с subjuntivo: Por mucho que **insistas**, no voy. Por muy listo que **sea**… Книжная **si bien** — только с индикативом. Повтор глагола: **Digas lo que digas**, no cambiaré de opinión.',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: 'Aunque ___ cansado, terminé el trabajo.', options: ['estaba', 'estuviera'], answer: 0, explain: 'Факт в прошлом — индикатив.' },
      { kind: 'choice', prompt: 'Aunque me lo ___, no lo creeré.', options: ['juras', 'jures'], answer: 1, explain: 'Даже если… — гипотеза, subjuntivo.' },
      { kind: 'input', prompt: 'Por mucho que ___, no lo vas a conseguir.', hint: 'intentar, tú', answers: ['lo intentes', 'intentes'], explain: 'Por mucho que + subjuntivo.' },
      { kind: 'choice', prompt: '___, iré a la fiesta.', options: ['Digan lo que digan', 'Dicen lo que dicen', 'Digan lo que dicen'], answer: 0, explain: 'Конструкция-повтор, оба глагола в subjuntivo: Digan lo que digan.' },
      { kind: 'choice', prompt: 'Si bien la idea ___ buena, es difícil de aplicar.', options: ['es', 'sea'], answer: 0, explain: 'Si bien — только индикатив.' },
      { kind: 'input', prompt: 'Por muy rico que ___, no es feliz.', hint: 'ser', answers: ['sea'], explain: 'Por muy … que + subjuntivo.' },
      { kind: 'choice', prompt: 'Aunque ___ millonario, seguiría trabajando.', options: ['soy', 'fuera', 'sería'], answer: 1, explain: 'Нереальное — imperfecto de subjuntivo.' },
      { kind: 'order', translation: 'Даже если пойдёт дождь, мы пойдём гулять.', answer: 'Aunque llueva, saldremos a pasear.' },
      { kind: 'choice', prompt: 'A pesar de que ___ mucho, no aprobó.', options: ['estudió', 'estudiara'], answer: 0, explain: 'Признанный факт в прошлом — индикатив.' },
      { kind: 'input', prompt: 'Por más que ___, no me convence.', hint: 'insistir, tú', answers: ['insistas'], explain: 'Por más que + subjuntivo.' },
      { kind: 'choice', prompt: 'Aunque ___ mañana, iré a trabajar.', options: ['estoy enfermo', 'esté enfermo'], answer: 1, explain: 'Даже если — гипотеза, subjuntivo.' },
      { kind: 'order', translation: 'Хотя я устал, я закончу работу.', answer: 'Aunque estoy cansado, terminaré el trabajo.' },
    ],
  },
  {
    id: 'es-perifrasis',
    language: 'es',
    level: 'C2',
    title: 'Глагольные перифразы',
    summary: 'Llevo dos años aquí, vuelvo a empezar, acabo de llegar.',
    theory: [
      {
        text: 'Перифразы — сочетания вспомогательного глагола с инфинитивом, герундием или причастием. Они передают оттенки, для которых в русском нужны наречия.',
        table: {
          head: ['Перифраза', 'Значение', 'Пример'],
          rows: [['acabar de + inf.', 'только что', 'Acabo de llegar.'], ['volver a + inf.', 'снова', 'Vuelvo a leer el libro.'], ['dejar de + inf.', 'перестать', 'Dejé de fumar.'], ['ponerse a + inf.', 'вдруг начать', 'Se puso a llorar.'], ['llevar + gerundio', 'уже (сколько времени)', 'Llevo dos años estudiando.'], ['seguir + gerundio', 'продолжать', 'Sigue lloviendo.'], ['ir + gerundio', 'постепенно', 'Voy entendiendo.'], ['tener + participio', 'уже сделано (итог)', 'Tengo escritas tres páginas.']],
        },
      },
      {
        heading: 'Llevar и seguir',
        text: '**Llevar** + время + gerundio = «уже столько-то делаю»: **Llevo** tres horas **esperando**. Отрицание — **sin + инфинитив**: Llevo dos días **sin dormir**. **Seguir** не сочетается с инфинитивом: не «sigue a llover», а **sigue lloviendo**.',
      },
    ],
    exercises: [
      { kind: 'choice', prompt: '___ dos años viviendo en Madrid.', options: ['Llevo', 'Sigo', 'Acabo'], answer: 0, explain: 'Сколько времени — llevar + gerundio.' },
      { kind: 'input', prompt: 'Acabo ___ hablar con tu madre.', answers: ['de'], explain: 'acabar de + inf. — «только что».' },
      { kind: 'choice', prompt: 'Después de leer la carta, se puso ___ llorar.', options: ['de', 'a', 'en'], answer: 1, explain: 'ponerse a — вдруг начать.' },
      { kind: 'input', prompt: 'Aunque le dije que parara, siguió ___.', hint: 'hablar', answers: ['hablando'], explain: 'seguir + gerundio.' },
      { kind: 'choice', prompt: 'Mi abuelo dejó ___ fumar hace diez años.', options: ['a', 'de', 'con'], answer: 1, explain: 'dejar de — перестать.' },
      { kind: 'input', prompt: 'Llevo tres noches sin ___.', hint: 'dormir', answers: ['dormir'], explain: 'llevar + sin + инфинитив.' },
      { kind: 'choice', prompt: 'Me equivoqué, así que ___ a hacer el ejercicio.', options: ['volví', 'llevé', 'dejé'], answer: 0, explain: 'volver a — снова.' },
      { kind: 'order', translation: 'Я жду тебя уже час.', answer: 'Llevo una hora esperándote.' },
      { kind: 'choice', prompt: 'El tren ___ de salir: lo hemos perdido.', options: ['acaba', 'vuelve', 'deja'], answer: 0, explain: 'acabar de — только что.' },
      { kind: 'input', prompt: 'Sigue ___ frío aunque ya es mayo.', hint: 'hacer', answers: ['haciendo'], explain: 'seguir + gerundio.' },
      { kind: 'choice', prompt: 'Poco a poco ___ entendiendo la gramática.', options: ['voy', 'llevo', 'acabo'], answer: 0, explain: 'ir + gerundio — постепенно.' },
      { kind: 'input', prompt: 'Ya tengo ___ dos capítulos.', hint: 'escribir', answers: ['escritos'], explain: 'tener + participio согласуется с предметом: escritos.' },
    ],
  },
  {
    id: 'es-probabilidad',
    language: 'es',
    level: 'C2',
    title: 'Будущее и condicional предположения',
    summary: '¿Qué hora será? — Serán las diez: как сказать «наверное».',
    theory: [
      {
        text: 'В испанском будущее время часто говорит не о будущем, а о **предположении**. Вместо «наверное» или «должно быть» глагол просто сдвигают на шаг вперёд.',
        table: {
          head: ['Уверенно', 'Предположение', 'Перевод'],
          rows: [['Son las diez.', 'Serán las diez.', 'Наверное, десять (сейчас).'], ['Ha salido.', 'Habrá salido.', 'Наверное, вышел (только что).'], ['Eran las diez.', 'Serían las diez.', 'Было, наверное, десять (тогда).'], ['Había salido.', 'Habría salido.', 'Наверное, уже вышел (к тому моменту).']],
        },
      },
      {
        heading: 'Как выбрать время',
        text: 'О настоящем — **futuro simple** (estará, tendrá). О недавнем прошлом, которое было бы в pretérito perfecto, — **futuro compuesto** (habrá llegado). О прошлом — **condicional** (estaría, sería). О том, что случилось раньше другого события в прошлом, — **condicional compuesto** (habría perdido).',
        examples: [
          { text: 'Juan no contesta. **Estará** durmiendo.', translation: 'Хуан не отвечает. Наверное, спит.' },
          { text: 'Ayer no vino. **Estaría** enfermo.', translation: 'Вчера он не пришёл. Наверное, болел.' },
        ],
      },
      {
        heading: 'Уступка',
        text: 'Futuro также означает «может, и…, но»: **Será** caro, pero merece la pena. — Может, это и дорого, но оно того стоит.',
      },
    ],
    exercises: [
      { kind: 'input', prompt: 'No sé qué hora es. ___ las tres.', hint: 'ser, предположение', answers: ['serán'], explain: 'О настоящем — futuro: serán.' },
      { kind: 'choice', prompt: 'Juan no contesta. ___ durmiendo.', options: ['Estará', 'Estaría', 'Esté'], answer: 0, explain: 'Предположение о настоящем — futuro.' },
      { kind: 'choice', prompt: 'Ayer no vino a clase. ___ enfermo.', options: ['Estará', 'Estaría', 'Está'], answer: 1, explain: 'Предположение о прошлом — condicional.' },
      { kind: 'input', prompt: 'Las llaves no están aquí. Las ___ en el coche.', hint: 'dejar, yo', answers: ['habré dejado'], explain: 'Недавнее прошлое — futuro compuesto: habré dejado.' },
      { kind: 'choice', prompt: '¿Dónde está Ana? — No sé, ___ ido al supermercado.', options: ['habrá', 'habría', 'haya'], answer: 0, explain: 'Предположение о только что случившемся: habrá ido.' },
      { kind: 'choice', prompt: 'Cuando llegué, ___ más o menos las once.', options: ['serán', 'serían', 'fueron'], answer: 1, explain: 'Предположение о прошлом — serían.' },
      { kind: 'input', prompt: '¿Cuántos años tiene esa mujer? — ___ unos cuarenta.', hint: 'tener, предположение', answers: ['tendrá'], explain: 'tener → tendrá.' },
      { kind: 'choice', prompt: '— Este restaurante es carísimo. — ___ caro, pero la comida es excelente.', options: ['Será', 'Sería', 'Sea'], answer: 0, explain: 'Уступка «может, и…, но» — futuro.' },
      { kind: 'choice', prompt: 'No encontró el camino: ___ el mapa en casa.', options: ['habrá dejado', 'habría dejado', 'dejará'], answer: 1, explain: 'Раньше другого прошлого события — condicional compuesto.' },
      { kind: 'input', prompt: 'El suelo está mojado. ___ llovido esta noche.', answers: ['habrá'], explain: 'Habrá llovido — наверное, шёл дождь.' },
      { kind: 'choice', prompt: '¿Qué ___ pasado? Hay mucha policía en la calle.', options: ['habrá', 'habría', 'ha'], answer: 0, explain: 'Догадка о недавнем: ¿Qué habrá pasado?' },
      { kind: 'order', translation: 'Наверное, он уже дома.', answer: 'Ya estará en casa.' },
    ],
  },
]
